### ISSUE TITLE
Resize issue on DriverAutomationTool v6.4.6

### ISSUE THREAD

**Issue by Vistaking** [maurice-daly/DriverAutomationTool#1]
Not able to resize this area 

![image](https://user-images.githubusercontent.com/26915656/77001387-196d9e00-6917-11ea-9f0e-ca7b9434920b.png)

**Comment by maurice-daly** [comment]
So you just want to be able to resize the columns?

**Comment by Vistaking** [comment]
Yes so I could see the entire words .

On Mar 19, 2020, at 6:37 AM, maurice-daly <notifications@github.com> wrote:

﻿

So you just want to be able to resize the columns?

**Comment by maurice-daly** [comment]
Are you running this on a 4K screen? Just curious. 

![image](https://user-images.githubusercontent.com/25844716/77225384-81fe8a00-6b66-11ea-9adc-a48533b14297.png)

Anyhow.. Resizing updated in the code. I'll post in the next build as I am waiting on an update from Lenovo.

**Comment by Vistaking** [comment]
Thank You . Just on a SurfaceBook .

On Mar 21, 2020, at 4:25 AM, maurice-daly <notifications@github.com> wrote:

﻿

Are you running this on a 4K screen? Just curious.

[image]<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25844716%2F77225384-81fe8a00-6b66-11ea-9adc-a48533b14297.png&data=02%7C01%7C%7C504f8e3088f24aa2631308d7cd8a848f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637203867114208984&sdata=1DhhkipossDoK76IrqgQA2h6v1KNlH5A7S9xRVRIFYc%3D&reserved=0>

Anyhow.. Resizing updated in the code. I'll post in the next build as I am waiting on an update from Lenovo.

**Comment by Vistaking** [comment]
Hi Maurice ..

Downloaded the 6.4.7 beta version of the tool . Seeing that I am only able to resize the columns on the
Make and Model tab. Tried resizing the others and I am not able to .


Thank you and Stay safe.
