### ISSUE TITLE
Driver download fails when "deployment platform" set to MDT

### ISSUE THREAD

**Issue by dperusich** [maurice-daly/DriverAutomationTool#109]
DAT Version: 6.4.8
Windows Server 2016 w/MDT

Updated to the latest release of DAT today, from verion 6.3.1, and when I attempt to download and import the Win10 1903 drivers for a Lenovo "ThinkPad T14 20S0 20S1" into MDT, the process fails to download the driver archive and says it successfully completes w/no errors. If I set the "deployment platform" to download only, it does download and extract the driver archive to the specified location. The MicrosoftDeploymentToolkit.psd1 has been imported and the MDT Share is correctly listed.

How can I troubleshoot this issue further, there is no verbose option anymore?

**Comment by istvanSA** [comment]
I have the same issue as the poster above

**Comment by dperusich** [comment]
I think it's also worth noting that with the current release, the folder created under out-of-box drivers in MDT is named "ThinkPad T14 20S0 20S1", yet the WMI query for this model returns "ThinkPad T14 Gen 1".  I suspect that will cause issues when using https://github.com/DeploymentResearch/DRFiles/blob/master/Scripts/ModelAliasExit.vbs to inject drivers based on Make/Model.

**Comment by istvanSA** [comment]
the 6.4.9 version doesn't download lenovo drivers either when using mdt

**Comment by gbmacman** [comment]
Ditto for Lenovo so far.  I will continue to test.  I noticed the deployment share setting does not save

**Comment by maurice-daly** [comment]
Can you download the latest EXE from the content folder. Issues with Lenovo downloads should be resolved.
