### ISSUE TITLE
Lenovo.. Selecting "Windows 10" doesn't default to newest drivers

### ISSUE THREAD

**Issue by russr123** [maurice-daly/DriverAutomationTool#111]
models dont even show up in the list, unless i select specific win versions..

**Comment by MJPhelan** [comment]
Much like HP and Microsoft, most Lenovo drivers seem to be specific to windows versions these days. This is due to a number of changes in the way Windows handles certain devices, GPU's being the most common.

**Comment by maurice-daly** [comment]
Lenovo are build specific. They do maintain older values for "Windows 10" in their XML, hence maintaining that option
