### ISSUE TITLE
WMI compression fails due to wrong DISM commandline options - missing quotation marks

### ISSUE THREAD

**Issue by luphisto** [maurice-daly/DriverAutomationTool#113]
DISM throws Error 87 when compressing drivers to WIM:

"C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\DismAction.log"

_Error: 87
DISM doesn't recognize the command-line option "Files\MSEndpointMgr\Driver". 
For more information, refer to the help by running DISM.exe /?.
The DISM log file can be found at C:\Windows\Logs\DISM\dism.log_
--------------------

"C:\windows\Logs\DISM\dism.log"

_2020-09-17 08:05:59, Error                 DISM   DISM.EXE: Failed validating command line: "C:\Windows\system32\Dism.exe" /Capture-Image /ImageFile:"C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\WimDriverFiles\DriverPackage.wim" /CaptureDir:C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\WimDriverFiles /Name:"Driver Automation Tool Package" /Description:"Driver Automation Tool Package" /Compress:max_ 
--------------------

<img width="813" alt="DAT_WIM_DISM_Error" src="https://user-images.githubusercontent.com/15671268/93427679-878f1f80-f8be-11ea-9429-0da3eec2f93f.png">

Solution would be to use quotes for the "/CaptureDir" parameter value as the default path contains spaces.

**Comment by burkebcn** [comment]
+1

**Comment by danielbessler** [comment]
+1

**Comment by maurice-daly** [comment]
This issue should be resolved within the latest exe.
