### ISSUE TITLE
flash64w.exe not found

### ISSUE THREAD

**Issue by nodiaque** [maurice-daly/DriverAutomationTool#114]
Hello,

6.4.9, it download a new version of dell flash64w.exe tools and upon extrat, it create a subfolder v3.3.8 in the temp folder. After that, the tools looks for it in \temp non recursive. The tool then hang there, not downloading or doing anything.

**Comment by maurice-daly** [comment]
Issue identified due to the flash bios utility having a subfolder within the source EXE;

![image](https://user-images.githubusercontent.com/25844716/97104731-0a6d7c00-16ae-11eb-9671-3fab5c63862d.png)

Fix in place. Update will be posted later today.
