### ISSUE TITLE
Support AdminService

### ISSUE THREAD

**Issue by benwa** [maurice-daly/DriverAutomationTool#115]
The `DriverAutomationTool` is one of the only solutions left in my environment that still uses the `ConfigMgrWebService`. If it can be updated to use the `AdministrationService`, then we can fully remove the `ConfigMgrWebService`.

**Comment by alayac** [comment]
https://msendpointmgr.com/2020/08/12/modern-driver-management-now-uses-adminservice-and-supports-cloud-management-gateway/

**Comment by benwa** [comment]
That is for the driver scripts, not DAT itself.

**Comment by alayac** [comment]
We may use the DAT differently.  I've used it for years but never installed or used the web service.  We just create and import Driver and BIOS packages with it.  The new Modern Driver Management will allow you to leverage packages created by DAT using Admin Service.

**Comment by maurice-daly** [comment]
Admin service support is provided here - https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1

**Comment by benwa** [comment]
Just so we're all on the same page. I'm talking about this facet of DAT
![image](https://user-images.githubusercontent.com/1351571/96874242-8613c280-143b-11eb-8a1a-2422d8315561.png)
