### ISSUE TITLE
Script is detecting me as Internal when I am external and is trying to connect to my Internal MP as opposed to my CMG

### ISSUE THREAD

**Issue by Ar5had07** [maurice-daly/DriverAutomationTool#116]
![image](https://user-images.githubusercontent.com/46709367/93580681-073ced00-f998-11ea-9f92-bbe39c879680.png)
![image](https://user-images.githubusercontent.com/46709367/93580753-19b72680-f998-11ea-93ea-a3cd593635eb.png)
![image](https://user-images.githubusercontent.com/46709367/93580883-48350180-f998-11ea-9c04-b5489f8baf1e.png)

Everything is set up according to the docs, to the dot.  But the script is failing to detect me as External and therefore tries to connect to my internal MP as opposed to my CMG.

But I am external, no VPN, client purely working over CMG.  Any ideas?

**Comment by Ar5had07** [comment]
Found something...
 The following snipet from the script

`$ActiveMPCandidates = Get-WmiObject -Namespace "root\ccm\LocationServices" -Class "SMS_ActiveMPCandidate"
				$ActiveMPInternalCandidatesCount = ($ActiveMPCandidates | Where-Object { $PSItem.Type -like "Assigned" } | Measure-Object).Count
				$ActiveMPExternalCandidatesCount = ($ActiveMPCandidates | Where-Object { $PSItem.Type -like "Internet" } | Measure-Object).Count
				
				switch ($ActiveMPInternalCandidatesCount) {
					0 {
						if ($ActiveMPExternalCandidatesCount -ge 1) {
							$Script:AdminServiceEndpointType = "External"
						}
						else {
							Write-CMLogEntry -Value " - Unable to determine AdminService endpoint type, bailing out" -Severity 3
		
							# Throw terminating error
							$ErrorRecord = New-TerminatingErrorRecord -Message ([string]::Empty)
							$PSCmdlet.ThrowTerminatingError($ErrorRecord)
						}
					}
					default {
						$Script:AdminServiceEndpointType = "Internal"
					}
				}
			}`

This will ALWAYS result in INTERNAL, as the $ActiveMPInternalCandidatesCount value is always greater than 0 so the SWITCH function will not work and it will default to the default value which is Internal.

**Comment by maurice-daly** [comment]
Incorrect forum for this post. Please post the issue within the MSEndpointMgr repo - https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1
