### ISSUE TITLE
Dell Precision 3630 Driver match issue.

### ISSUE THREAD

**Issue by buckimateusz** [maurice-daly/DriverAutomationTool#118]
Was having 3 different packages in Config mgr A05, A07 and A09 versions for Dell Precision 3630. The Invoke-CMApplyDriverPackage.ps1 script failed to match the newest one. Script version 4.0.2.

Log attached. 
[ApplyDriverPackage.log](https://github.com/maurice-daly/DriverAutomationTool/files/5256548/ApplyDriverPackage.log)

**Comment by maurice-daly** [comment]
Can you please raise this issue in the repo here - https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1
