### ISSUE TITLE
Error in DISM Command

### ISSUE THREAD

**Issue by JoelDKraft** [maurice-daly/DriverAutomationTool#119]
Line 17312 of 6.4.9 is missing quotation marks around the /CaptureDir path:

$DismArgs = "/Capture-Image /ImageFile:`"$(Join-Path -Path $WimTempLocation -ChildPath DriverPackage.wim)`" /CaptureDir:$WimTempLocation /Name:`"$WimDescription`" /Description:`"$WimDescription`" /Compress:max"

Line 17324 indicates that the log is in the extract directory, when it is actually in the temp directory:

global:Write-LogEntry -Value "Error: Failed to locate DriverPackage.wim. Please review the DISM log file located in $DriverExtractDest" -Severity 1

**Comment by JoelDKraft** [comment]
PS. It would be great if the expanded drivers in the WimDriverFiles folder were deleted immediately after the WIM has been created. If there are a lot of updates, the gigs of data can rack up fast.

**Comment by maurice-daly** [comment]
Issue already resolved within the latest available exe.
