### ISSUE TITLE
Bad Switch Statement Default Condition when retrieving available driver package information

### ISSUE THREAD

**Issue by Staja** [maurice-daly/DriverAutomationTool#124]
In [Invoke-CMApplyDriverPackage.ps1:1991](https://github.com/maurice-daly/DriverAutomationTool/blob/master/Content/Invoke-CMApplyDriverPackage.ps1#L1991)
`"Default"` should be `Default` otherwise the script breaks when not running with parameter `-XMLPackage`
See [About Switch](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_switch?view=powershell-5.1).

For anyone else troubleshooting errors, the error you might receive in your ApplyDriverPackage.log is:
` - An error occurred while calling  for a list of available driver packages. Error message: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.`

**Comment by Staja** [comment]
Fixed at https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1
Version of script in this repository is old...

**Comment by MEConfigMgr** [comment]
Thank you so much, Staja! This script worked like a charm!

**Comment by Staja** [comment]
@MEConfigMgr I didn't actually make that script, it's just the script in this repo is old
They moved to a new repository for the PowerShell scripts as noted in https://msendpointmgr.com/2020/08/12/modern-driver-management-now-uses-adminservice-and-supports-cloud-management-gateway/

https://github.com/maurice-daly/DriverAutomationTool/issues/73

**Comment by MEConfigMgr** [comment]
> @MEConfigMgr I didn't actually make that script, it's just the script in this repo is old
> They moved to a new repository for the PowerShell scripts as noted in https://msendpointmgr.com/2020/08/12/modern-driver-management-now-uses-adminservice-and-supports-cloud-management-gateway/
> 
> #73

Got it! Thanks again!
