### ISSUE TITLE
Add the possibility to search for HP drivers, regardless of the version.

### ISSUE THREAD

**Issue by berny-rode** [maurice-daly/DriverAutomationTool#128]
Added the possibility to search for HP drivers, regardless of the version.

Unfortunately HP does not offer all drivers in all versions. So it can happen that drivers for a certain device exist in version 1609, but no longer in version 1909. But also the other way around. Drivers exist for the version 2004 but not for the version 1909.

We set the drivers for the version 1609 for the version 1909 and they work just as well in 99.9% of the cases :-)

Currently, if HP drivers for a certain device not exist for the currently used Windows version, drivers  must be searched for each version and then converted to the required version via "Package Management".

A selection --> Download Type --> Operating System (Windows 10) --> (HP selectable) HP (search for all known devices) --> + (new selection option) create driver packages for Windows version X

Translated with www.DeepL.com/Translator (free version)

**Comment by equillibrium** [comment]
Yeah that would be a really nice feature

**Comment by MJPhelan** [comment]
The challenge there is that some (not all) of those drivers, actually won't work on newer windows build. Indeed they may even cause your OSD task sequence to fail completely. Lenovo and Microsoft devices give the same challenge.

**Comment by maurice-daly** [comment]
Unfortunately the filters are there in order to limit what you see in terms of support. I could recode the option to show all drivers under the Windows 10 option, which might cause some confusion though as it would auto select all models against all builds. 

For now, if you want to confirm availability per model, you can always check HP SCCM listings here - https://ftp.hp.com/pub/caps-softpaq/cmit/HP_Driverpack_Matrix_x64.html

**Comment by zakgodwin** [comment]
I know this is a closed issue but how do you automate downloading drivers when for example we have some models that only exist for 1809 were now a 20H2 shop plus we have some Dell's that we need drivers for. I've been manually renaming the DatSettings.xml but that process is somewhat of a pita and I still wouldn't know how to make that work with the service script.
