### ISSUE TITLE
Lenovo Models broken again

### ISSUE THREAD

**Issue by MJPhelan** [maurice-daly/DriverAutomationTool#131]
![image](https://user-images.githubusercontent.com/17612193/96710810-7ee5a980-1394-11eb-995a-2eb7b8bccc5b.png)

We have no proxy, and no firewall blocks of any kind as can be evidenced by my ability to manually get to the XML file

![image](https://user-images.githubusercontent.com/17612193/96711000-c53b0880-1394-11eb-9774-00b44e0df547.png)

**Comment by mkocaaga** [comment]
i have the same issue. DELL, HP and Microsoft work fine, only Lenovo does not work

**Comment by jeffying** [comment]
Thought it was just me, seems to be broken for lenovo also on previous versions as I tried some earlier builds as well with no luck

**Comment by MJPhelan** [comment]
Does anyone have a copy of the Catalogv2.xml in their temp folder from 2+ weeks ago?

**Comment by mkocaaga** [comment]
how or who can solve this problem?

**Comment by dydigital** [comment]
I am having the same issue with lenovo drivers

**Comment by etsmi** [comment]
`						if ($global:ProxySettingsSet -eq $true) {
                            $LenovoModelXMLTemp = Invoke-WebRequest -Uri $LenovoXMLSource @global:InvokeProxyOptions
                            $LenovoModelXMLTemp = $LenovoModelXMLTemp -creplace  '^[^<]*<', '<'
							[xml]$global:LenovoModelXML = $LenovoModelXMLTemp
						} else {
                            $LenovoModelXMLTemp = Invoke-WebRequest -Uri $LenovoXMLSource 
                            $LenovoModelXMLTemp = $LenovoModelXMLTemp -creplace  '^[^<]*<', '<'
							[xml]$global:LenovoModelXML = $LenovoModelXMLTemp
						}`

**Comment by etsmi** [comment]
if ($global:ProxySettingsSet -eq $true) {
                            $LenovoModelXMLTemp = Invoke-WebRequest -Uri $LenovoXMLSource @global:InvokeProxyOptions
                            $LenovoModelXMLTemp = $LenovoModelXMLTemp -creplace  '^[^<]*<', '<'
							[xml]$global:LenovoModelXML = $LenovoModelXMLTemp
						} else {
                            $LenovoModelXMLTemp = Invoke-WebRequest -Uri $LenovoXMLSource 
                            $LenovoModelXMLTemp = $LenovoModelXMLTemp -creplace  '^[^<]*<', '<'
							[xml]$global:LenovoModelXML = $LenovoModelXMLTemp
						}

**Comment by mkocaaga** [comment]
@etsmi what should I do with this info?

can anyone please tell how to fix this problem? Who can help here?

**Comment by etsmi** [comment]
replace

						if ($global:ProxySettingsSet -eq $true) {
							[xml]$global:LenovoModelXML = Invoke-WebRequest -Uri $LenovoXMLSource @global:InvokeProxyOptions
						} else {
							[xml]$global:LenovoModelXML = Invoke-WebRequest -Uri $LenovoXMLSource
						}

with 

					if ($global:ProxySettingsSet -eq $true) {
                        $LenovoModelXMLTemp = Invoke-WebRequest -Uri $LenovoXMLSource @global:InvokeProxyOptions
                        $LenovoModelXMLTemp = $LenovoModelXMLTemp -creplace  '^[^<]*<', '<'
						[xml]$global:LenovoModelXML = $LenovoModelXMLTemp
					} else {
                        $LenovoModelXMLTemp = Invoke-WebRequest -Uri $LenovoXMLSource 
                        $LenovoModelXMLTemp = $LenovoModelXMLTemp -creplace  '^[^<]*<', '<'
						[xml]$global:LenovoModelXML = $LenovoModelXMLTemp
					}

if you do not know how, please wait for either lenovo to fix their xml file, or wait for maurice do magic tricks.

**Comment by mkocaaga** [comment]
@etsmi 
thanks for your tip, but it still doesn't work.
I have adjusted the PS under "C: \ Program Files \ MSEndpointMgr \ Driver Automation Tool \ DriverAutomationTool.ps1".

do I have to adjust something else?

**Comment by maurice-daly** [comment]
Fix uploaded. Please download the exe and I will update the MSI later today.
