### ISSUE TITLE
Issue with HP models not getting Known Models selected in console.

### ISSUE THREAD

**Issue by richierichman** [maurice-daly/DriverAutomationTool#136]
Hi All
I am on the latest version 6.4.9 (hotfix) and I notice that previously I had Hewlett-Packard as manufacturer for all HP models and the new version shows only HP as manufacturer. I re-downloaded all drivers into SCCM so they now show as HP for Manufacturer, but I had to manually pick all the models that we use. None of the known HP devices are being picked as known models like the Lenovo devices. Am I missing a setting somewhere? Any help would be appreciated. Thanks in advance. 
Rich

![image](https://user-images.githubusercontent.com/1811335/98628926-cfd13800-236b-11eb-886d-d17ed9dcfca8.png)

**Comment by sk1ppy81** [comment]
I have the same issue HP models not auto selecting in version 6.4.9. Also tried the BETA 6.5.0 and same results

**Comment by richierichman** [comment]
> I have the same issue HP models not auto selecting in version 6.4.9. Also tried the BETA 6.5.0 and same results

I got mine working again. I had to remove all the HP drivers that were in SCCM and re-download them via the tool. It is now picking up the HP models. Also the manufacture name changed from Hewlett Packard to HP. Try deleting the driver packages in SCCM and re-downloading them in the Driver tool.

**Comment by richierichman** [comment]
Had to re-add all the driver packages back into sccm and the tool picked them up again.
