### ISSUE TITLE
Lenvo xml error with 6.4.9

### ISSUE THREAD

**Issue by magic280z** [maurice-daly/DriverAutomationTool#137]
Lenovo xml is broken again it downloads the xml, but it unable to convert.

<![LOG[Error: Cannot convert value "???<?xml version="1.0" encoding="UTF-8"?>
<XML data removed>
<![LOG[Info: Reading driver pack URL - https://download.lenovo.com/cdrt/td/catalogv2.xml]LOG]!><time="09:40:22.613 -300" date="11-10-2020" component="DriverAutomationTool" context="username" type="1" thread="7488" file="">

**Comment by NFCES** [comment]
Have similar issue, but with a proxy, which I do not use so not sure why I would get this error. This happens only for Lenovo.

**Comment by dtheisse** [comment]
Hello, I had the same problem and I resolved it to clean the Temp Folder.
For example:
C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\

**Comment by NFCES** [comment]
Nope, tried that already. Also performed a clean uninstall and reinstall as well and installing on fresh system.

**Comment by dtheisse** [comment]
Do you have a prior Version of Driver Automation Tool installed?
Like:
C:\Program Files\SCConfigMgr\Driver Automation Tool\Temp\

Did you Changed the DriverAutomationTool.exe?

**Comment by dlisa29** [comment]
Any way to resolve this.  I'm having the same issue with Lenovo models.  I'm not using a proxy server but the software errors out trying to read the driver pack url.  Cleaning the temp folders didn't help.

**Comment by Hetti-** [comment]
I resolved this issue today with replacing the .exe with the latest version
from github.

dlisa29 <notifications@github.com> schrieb am Mi., 11. Nov. 2020, 16:33:

**Comment by dlisa29** [comment]
Thanks for the response that did the trick.

**Comment by magic280z** [comment]
I tried a few different versions latest and older at the time.  I tried latest today and it works exe today and it is happy.
