### ISSUE TITLE
Bug at line 11426

### ISSUE THREAD

**Issue by Gdordain** [maurice-daly/DriverAutomationTool#15]
Hello,

With the change of the website URI you need to update the line 11426 to :
$NewRelease = (Invoke-WebRequest -Uri "https://msendpointmgr.com/wp-content/uploads/tools/DriverAutomationToolRev.txt" -UseBasicParsing).Content

**Comment by maurice-daly** [comment]
Updated in the latest beta build. There actually was no need to change this as we had redirection enabled on the old domain.
