### ISSUE TITLE
Latitude 9520 driver not found 

### ISSUE THREAD

**Issue by ps959** [maurice-daly/DriverAutomationTool#210]
I'm trying to import the model Latitude 9520 and it's not being found by the Driver Management. https://www.dell.com/support/home/en-pk/product-support/product/latitude-15-9520-2-in-1-laptop/drivers

What triggers new models showing up in the Driver Automation Tool?

**Comment by dsolodow** [comment]
It looks at a Dell CAB file that it pulls from their site. You can force a refresh by:

1. close Driver Automation Tool (DAT)
2. under where you have DAT installed, look for a **Temp** folder
3. delete the two _DriverPackCatalog_ files in that **Temp** folder
4. launch DAT and select Dell
5. click _Find Models_

I did that a bit ago and the Latitude 9520 shows up.

**Comment by ps959** [comment]
Thank you, this worked.
