### ISSUE TITLE
HP manufacturer grayed out and not checked, Microsoft grayed out and checked.

### ISSUE THREAD

**Issue by TheGunslingerRG** [maurice-daly/DriverAutomationTool#250]
This seems to happen every few days. When we open the tool, usually the Dell manufacturer selection is unchecked and grayed out. This is a bigger issue for us since we generally use Dell computers. Today, the Dell box was checked, but the HP was unchecked and grayed out. Of course today we started ordering some HPs!

In the past I've fixed it by backing up the settings and re-installing. Today, that doesn't work. No matter what I try, HP is grayed out and unselected. Are there other things I can try to get it to work?

**Comment by dfishel** [comment]
Try changing the Windows OS selection. I believe that some of the options for manufacturer change depending on what OS is selected for windows 10 vs a windows 10 build number.

**Comment by TheGunslingerRG** [comment]
That was it... I should have tried that first. I was able to get around it by editing the settings file and changing the HP option from false to true, but this makes more sense!
