### ISSUE TITLE
HP Client Catalog moved?

### ISSUE THREAD

**Issue by Southdakotan** [maurice-daly/DriverAutomationTool#26]
Trying to set up the tool, and it fails finding the HpCatalogForSms.latest.cab for HP drivers. I found this article saying it moved: https://hpia.hpcloud.hp.com/downloads/sccmcatalog/HpCatalogForSms.latest.cab.  Is this accurate, and should I be able to modify the scripts to point to that?

**Comment by kean83** [comment]
For me it works as usual:
"Info: Downloading HP driver pack cabinet file from https://ftp.hp.com/pub/caps-softpaq/cmit/HPClientDriverPackCatalog.cab"

**Comment by Southdakotan** [comment]
Must be something on my network blocking it. Thanks!

**Comment by teh1tn1nj4** [comment]
What did this end up being?  I'm getting the same exact error.

**Comment by Southdakotan** [comment]
I gave up on it and implemented HP's tools, SSM. https://ftp.hp.com/pub/caps-softpaq/cmit/HP_SSM.html
