### ISSUE TITLE
Dell drivers stopped downloading

### ISSUE THREAD

**Issue by mmtechconsulting** [maurice-daly/DriverAutomationTool#336]
This is now happening in my Production environment and lab so it cant be the automation tool.
Anyone else having this issue? Has Dell done something on their catalogues?

this is the error i get:

Get-Item : Cannot find path '\\xxxxxxxxxxxxxxxxxxxxx' because it does not exist.
At line:18529 char:81
+ ... e size:  $((Get-Item -Path $($DownloadRoot + $Model + '\Driver Cab\'  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\cm1\MDM_Temp\...0-A13-VGY73.CAB:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

**Comment by mmtechconsulting** [comment]
Microsoft drivers are dowloading fine - Dell BIOS is also downloading ok

**Comment by einbahn** [comment]
same here

**Comment by hamlingraham** [comment]
Same Here.

**Comment by bbrownchg** [comment]
I tried downloading a CAB for a Latitude 5490 that failed out; it even fails out from the link directly on their site: https://www.dell.com/support/kbdoc/en-us/000122499/latitude-5490-windows-10-driver-pack.

Clearly a Dell problem, not sure who exactly to notify of the issue. Does anyone know Twitter handles or anything of anyone from the Dell side that maintains these?

**Comment by desmoflo** [comment]
Hello,

Any news regarding this issue ?

Still the same problem .

**Comment by mmtechconsulting** [comment]
Hi all - seems to be a dell catalogue issue

https://twitter.com/modaly_it/status/1517492046285656066

**Comment by ps959** [comment]
Still broken. I'm getting the same error. Tried multiple models. Running 7.1 

Get-Item : Cannot find path '\\XXX\Drivers-Source\Dell\Latitude 7420\Driver Cab\7420-win10-A08-Y56C2.CAB' because it does not exist.
At line:18617 char:81
+ ... e size:  $((Get-Item -Path $($DownloadRoot + $Model + '\Driver Cab\'  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\files.cornell...0-A08-Y56C2.CAB:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
