### ISSUE TITLE
Issue trying to update DriverAutomationTool

### ISSUE THREAD

**Issue by 888mxc** [maurice-daly/DriverAutomationTool#344]
Hi, 

Trying to update my MSEndpointMgr tool but it seems to be throwing an error when I click "Update Tool". See attached screenshots. I am new to using this tool which I have inherited.

Any assistance would be much appreciated.
![image](https://user-images.githubusercontent.com/105911845/169483138-b57efccb-cb7f-4ea4-8c58-e6a218b5b91e.png)

**Comment by ImaBadCoder** [comment]
I am getting this same message. Any updates or work arounds?

**Comment by 888mxc** [comment]
Still no dice trying to fix this. Anyone able to figure this one out? Much appreciated!

**Comment by 888mxc** [comment]
> I am getting this same message. Any updates or work arounds?

I've ended up manually updating it.

Downloaded the files as ZIP from: https://github.com/maurice-daly/DriverAutomationTool

Extracted the zip file > Copied the 3 files from the Current Branch folder (the exe/config/md5) > copied to the install location of the driver tool (default location: C:\Program Files\MSEndpointMgr\Driver Automation Tool)
