### ISSUE TITLE
Dell Latitude 5430 Drivers aren't available

### ISSUE THREAD

**Issue by carvius87** [maurice-daly/DriverAutomationTool#347]
Hello everyone,

i have tried to import the drivers for Latitude 5430, but they are missing (only different model 5430 Ragged).

Main problem is, that catalog file is from 05/10/2022. The Latitude 5430 can't be found in the files.

I have asked the Dell Support, when the Update for the Catalog File will be happen, but they don't know.

Also Dell Support meant, that the Link https://downloads.dell.com/catalog/ ist outdatet.

I schould use the following link: ftp://ftp.dell.com/catalog/DellSDPCatalogPC.cab

Does anyone know, how i will be able to import the Latitude 5430?

Thanks
BR

**Comment by TazwellJ** [comment]
Same problem here.  They do have a release schedule though.  According to https://www.dell.com/support/kbdoc/en-us/000181417/driver-pack-release-schedule they are scheduled to release driver packs for both Windows 10 and 11 for the 5430 sometime this month (2nd or 4th Tuesday).

**Comment by carvius87** [comment]
Thank you TazwellJ for the valuable information. I was looking for this.
Unfortunately, it looks like it will take even longer. So I have to build a workaround tasksequence.

BR

**Comment by danielbessler** [comment]
I miss the Precision 5770 and Latitude 5430 drivers in DAT. 

My solution was to delete following three files before I opened DAT

Under:
C:\Program Files\MSEndpointMgr\Driver Automation Tool Dell\Temp
DriverPackCatalog.cab
DriverPackCatalog.xml

C:\Program Files\MSEndpointMgr\Driver Automation Tool Dell\Settings
OEMLinks.xml


Hope that will help you as well. 

Regards

**Comment by carvius87** [comment]
Hi Daniel,

thanks. Now i DAT found the Latitude 5430 drivers.

BR

**Comment by TazwellJ** [comment]
I think Dell may have changed the format of their xml file.  All the drivers I pulled down today (including the 5430) show the version of the driver as the model of the machine (i.e. 5430 instead of A02).  Baseboardproduct value I pulled from an actual machine (01Y2TP) doesn't match what is in the file for the 5430 (0B04;0B05)

**Comment by carvius87** [comment]
Hi @TazwellJ ,
yes, i discovered the same changes and issues. For now the drivers can be downloaded, but the latest "Intel Rapid Storage" driver is missing. I have to install the device with BIOS Setting AHCI and not with RAID ON.

**Comment by carvius87** [comment]
Drivers now available
