### ISSUE TITLE
Latitude 3320 is missing

### ISSUE THREAD

**Issue by jisis83** [maurice-daly/DriverAutomationTool#349]
I cannot find the Latitude 3320, 

SystemSKU: 0A88

https://www.dell.com/support/home/sv-se/drivers/driversdetails?driverid=v80cm&oscode=wt64a&productcode=latitude-13-3320-laptop

**Comment by carvius87** [comment]
Hi,
on my infrastructure i can find "Latitude 3320". Are you using the actual OEMLinks.xml File?
Driver Automation Tool downloads drivers directly with the links in this file. 

https://downloads.dell.com/catalog/

to my regret dell has not yet added my model Latitude 5430

BR

**Comment by jisis83** [comment]
After a restart of the newly installed tool it appeared. Thanks!
