### ISSUE TITLE
Lenovo driver download logic needs some work

### ISSUE THREAD

**Issue by aimar115** [maurice-daly/DriverAutomationTool#35]
While Downloading driver packages for W10 1909 it selects driver package based on release date not windows version.
Attatched Image:

![image](https://user-images.githubusercontent.com/49677600/83755320-12347180-a676-11ea-8573-9a218501a286.png)

**Comment by aimar115** [comment]
Picture from Log File: 
![image](https://user-images.githubusercontent.com/49677600/83761598-347ebd00-a67f-11ea-9742-6ac9fb4bcf0f.png)

**Comment by aimar115** [comment]
Lenovo uses "_" to separate BuildVersions in their Driver filenames, I'm thinking that we could use that to our advantage.
Script row 12293:
`						$Win10VersionLink = $MatchingLink | Where-Object {
							$_ -match "_"+$($OSVersion)+"_"
						} | Select-Object -Last 1`
I Will try that later.

**Comment by aimar115** [comment]
After making that change the script works as intended.
![image](https://user-images.githubusercontent.com/49677600/83845162-fd58ec00-a710-11ea-86fe-931440d5f6bb.png)

**Comment by aimar115** [comment]
After making the change script works as intended:
![image](https://user-images.githubusercontent.com/49677600/83853376-e10f7c00-a71d-11ea-9d6f-d4cc18ea31bf.png)

Also had to add:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

**Comment by maurice-daly** [comment]
Lenovo download issues have since been resolved. Closing.
