### ISSUE TITLE
Driver Download for Surface Laptop 4 Windows 11 21H2

### ISSUE THREAD

**Issue by Mercwerd** [maurice-daly/DriverAutomationTool#369]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/44645690/178834082-6b412a86-fa80-4dfe-9448-9541b279aead.png">

It looks like the redirect for https://aka.ms/SurfaceLaptop4/Intel/22000 is broken.  It tries to redirect to "https://download.microsoft.com/download/f/7/0/f70b3d0a-59b1-4842-9130-0c152bb738ba/SurfaceLaptop4_Win11_22000_22.042.17187.0.m" (no "si" at the end).

I understand this is a Microsoft issue, but wondered if there's a workaround since I can actually download the MSI needed.

Thank you

**Comment by maurice-daly** [comment]
Please download the latest release  - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe
