### ISSUE TITLE
7.1.4 "-Fast for retrieving objects without loading lazy properties"

### ISSUE THREAD

**Issue by MrRobot5000** [maurice-daly/DriverAutomationTool#370]
Since upgrading to 7.1.4 I've been getting the following error...

`'Get-CMDriverPackage' supports -Fast for retrieving objects without loading lazy properties. Loading lazy properties can cause significant performance penalties. If it is not necessary to utilize the lazy properties in the returned object(s), -Fast should be used. This warning can be disabled by setting $CMPSSuppressFastNotUsedCheck = $true. `

It does take a much more time to create driver packages in this state.

What should be done to correct this?
I'm not certain as to where I need to populate the "-Fast" at.

Thank you!

**Comment by MrRobot5000** [comment]
I fell back to 7.0.4 and it seems to perform fast as it did before. However, I still am seeing this message/error displayed. I haven't noticed it previously.

**Comment by MrRobot5000** [comment]
I'm just ignoring it now and moved up to version 7.1.7. It seems to be doing much better.

**Comment by maurice-daly** [comment]
Updated in latest version - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe
