### ISSUE TITLE
Can we manually update the Microsoft Surface product list?

### ISSUE THREAD

**Issue by NoDowt** [maurice-daly/DriverAutomationTool#375]
As I understand it, you periodically update the download options for the Microsoft surface products. It seems that there is a number of issues on here requesting some newer Surface models be added to the list.

Is there a way for us to update these ourselves?

**Comment by maurice-daly** [comment]
Switched over to using David Segura's source. Please download 7.1.8 - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe
