### ISSUE TITLE
7.1.7 is not stating

### ISSUE THREAD

**Issue by equillibrium** [maurice-daly/DriverAutomationTool#380]
Can't seem to find a way to start newer verisons of DAT.
Tried both in the Current branch folder and copying it to DAT installed locally in Program FIles.

All I see is this:
![image](https://user-images.githubusercontent.com/5002815/186175497-5f673902-3241-4f7d-b749-5a70bf4ea155.png)

**Comment by Grabou** [comment]
Same here. 7.1.7 is not extracting files anymore.

**Comment by equillibrium** [comment]
The latest verison that starts correctly is Beta Build 7.1.1

**Comment by maurice-daly** [comment]
Please use the latest release here - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe

**Comment by equillibrium** [comment]
> Please use the latest release here - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe

No luck starting it with exe for some reason - same blank white window as on  the screenshot above. Managed to succesfully start it with ps1 though
