### ISSUE TITLE
7.1.8 - Surface_Laptop_3_1867_1868

### ISSUE THREAD

**Issue by 67dbc** [maurice-daly/DriverAutomationTool#381]
Unfortunately you can't include : (colon in the path name). This needs to be corrected.
![7 1 8](https://user-images.githubusercontent.com/92107779/187541401-97df0f1b-d794-429f-a05b-87189a33d280.png)

**Comment by jsotomar** [comment]
Having the same problem Surface Laptop 4 drivers. Both Win10 & Win11 drivers

![image](https://user-images.githubusercontent.com/112584898/187771670-6d5f878b-8bdf-4601-b859-c661d2fac310.png)

**Comment by maurice-daly** [comment]
Fix coming in the morning.

**Comment by maurice-daly** [comment]
![image](https://user-images.githubusercontent.com/25844716/187966170-3cc0403b-4621-4bd4-b959-ade4265abd86.png)

Hotfix inbound shortly

**Comment by maurice-daly** [comment]
Hotfix here - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe

**Comment by jsotomar** [comment]
> Hotfix here - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe

Thanks, able to download now. Have a great day!
