### ISSUE TITLE
7.1.8 MSI defaults to wrong directory

### ISSUE THREAD

**Issue by dsolodow** [maurice-daly/DriverAutomationTool#382]
The default install path for the MSI is:
C:\Program Files\MSEndpoingMgr.com\Driver Automation Tool
should be:
C:\Program Files\MSEndpointMgr.com\Driver Automation Tool

previous versions of the installer went to:
C:\Program Files\MSEndpointMgr\Driver Automation Tool
but I'm assuming adding the .com is intended.

**Comment by maurice-daly** [comment]
https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe

**Comment by dsolodow** [comment]
I just downloaded the MSI from https://github.com/maurice-daly/DriverAutomationTool/blob/master/Driver%20Automation%20Tool.msi and verified the MD5 matches the updated md5 file, and it's still trying to install to "C:\Program Files\MSEndpoingMgr\Driver Automation Tool\"

**Comment by maurice-daly** [comment]
Typo. Updated the MSI. It should install to C:\Program Files\MSEndpointMgr\Driver Automation Tool
