### ISSUE TITLE
7.1.8 - Microsoft drivers for some Windows 10 builds not detected

### ISSUE THREAD

**Issue by dsolodow** [maurice-daly/DriverAutomationTool#383]
I'm assuming that it's parsing the JSON for the Windows 10 Build number. 
Windows 10 1909 should be 18363 and there are several drivers in the 22.08.29 version of the OSDCatalogMicrosoftDriverPack.json for Windows 10 18363.
However, selecting that option says no models found.
The DriverAutomationTool.log shows:
![image](https://user-images.githubusercontent.com/7574074/187549774-44ff3cbb-b5cf-4682-9aa1-88927d153f16.png)

**Comment by maurice-daly** [comment]
Hotfix now available here - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Current%20Branch/7.1.8/DriverAutomationTool.exe
