### ISSUE TITLE
Dell SKU missing in sccm package

### ISSUE THREAD

**Issue by TheDjGogo2000** [maurice-daly/DriverAutomationTool#397]
MSEndpointMgr 7.1.9 | SCCM 2203
when i create a ConfigMgr - Standard Pkg for Dell Latitude 3520 with the 3 identifiers (0A7C;0A85;0B21), in SCCM, the description of the package is : (Models included:0A7C;0A85)
My model is 0B21 and it was ignored by the powershell script.

Regards,

**Comment by maurice-daly** [comment]
Please log this issue against the https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1 script.
