### ISSUE TITLE
Unable to use the tool tabs

### ISSUE THREAD

**Issue by Kadavergu-Anudeep** [maurice-daly/DriverAutomationTool#4]
While i am opening the tool , it is going into infinite loading. Is there any software or hardware requirements to run this tool?

**Comment by maurice-daly** [comment]
The tool requires at least PowerShell 5.0 and Internet Explorer (do not remove the feature as it uses the underlying engine). You should also be an admin, and of course have internet access on the machine. Run the verbose mode for more output to help you troubleshoot issues in your environment,
