### ISSUE TITLE
Fujitsu Driver Support

### ISSUE THREAD

**Issue by azulol** [maurice-daly/DriverAutomationTool#40]
Since Driver Automation Tool doesn´t support Fujitsu Drivers, but the Invoke-CMApplyDriverPackage.ps1 script does. 
How do i create Fujitsu Driver Packages in SCCM so the script will work in the task sequence?
Is there an instruction or something?

Thank you

**Comment by maurice-daly** [comment]
You can create custom packages for other vendors. This section is included in the DAT documentation, and requires your own extension of the detection script in some circumstances. Fujitsu did initially express interest in providing model feeds, so if you have a rep, please let them know as we could automate this.
