### ISSUE TITLE
Infinite Bits loop on error ?

### ISSUE THREAD

**Issue by mathieuchateau** [maurice-daly/DriverAutomationTool#405]
Hello,

When issue arise, it tends to stick in infinite BITS loop:
Version 7.1.9

![image](https://user-images.githubusercontent.com/4478521/196694857-f7cbde3b-c33b-4b8b-8312-dcddc2f147ea.png)

The way I found to break this loop without loosing current work was to restart BITS service 30mn later

![image](https://user-images.githubusercontent.com/4478521/196693799-4b287729-77a5-41d4-adf2-e84ff8628a6c.png)

**Comment by Wavee7** [comment]
Same problem there when trying to download drivers for Lenovo ThinkPad T14s Gen 2.

**Comment by maurice-daly** [comment]
Unable to reproduce issue using details provided.
