### ISSUE TITLE
OSDCatalogMicrosoftDriverPack.json needs updating

### ISSUE THREAD

**Issue by mmtechconsulting** [maurice-daly/DriverAutomationTool#414]
It seems that Microsoft has updated their surface models links so some models are now failing to download.

I do not mind contributing to project however i have no clue how to go about doing this.

Some googling revealed that OSDeploy has the latest at: 

https://github.com/OSDeploy/OSD/blob/master/Catalogs/OSDCatalog/OSDCatalogMicrosoftDriverPack.json

I tried to change my local OEMLinks.dat to point to that however it did not work.

Any ideas how i can move forward a bit?

**Comment by mmtechconsulting** [comment]
@maurice-daly  What is the process updating this? If there is any way i can help please let me know.

**Comment by maurice-daly** [comment]
JSON updated.
