### ISSUE TITLE
Support for Surface Book 3 

### ISSUE THREAD

**Issue by EGGLAS** [maurice-daly/DriverAutomationTool#42]
Hello, 

Would it be possible to get an update for XML file to get support for Surface Book 3?

**Comment by jonnyh26** [comment]
i also require this as well :-)

**Comment by chaosisbliss** [comment]
Yes, would it be possible to add this as well? Thanks for your time and support to this tool.

**Comment by EGGLAS** [comment]
Any ETA when support for Surface Book 3 will be added? 
Thanks for a really great tool.

**Comment by DewayneHyatt** [comment]
I'd also like to chime in here that SB3 drivers would be great. I realize you have to do this manually :(

**Comment by maurice-daly** [comment]
Updated Surface model list now available in the latest release.
