### ISSUE TITLE
List of URLs / IPs ?

### ISSUE THREAD

**Issue by NorbertBauer** [maurice-daly/DriverAutomationTool#433]
Hi

Do you have a list of URLs / IPs that are used by the tool?
I have some customers, where the security department do no allow them to use this tool.
If we have a list/documentation that states where it needs access to and maybe which information is transferred to or from this URL, then we may get a bypass for this specific connection on their firewall.

Thanks
Norbert

**Comment by HermanGB** [comment]
These are the URL's I had to whitelist to get it working. 

https://download.microsoft.com
https://dl.dell.com
https://en.community.dell.com
https://ftp.hp.com
https://hpia.hpcloud.hp.com
https://download.lenovo.com
https://raw.githubusercontent.com
https://support.microsoft.com

**Comment by maurice-daly** [comment]
If you look at the github content here - https://github.com/maurice-daly/DriverAutomationTool/blob/master/Data/OEMLinks.xml, you will see the URLs used by the tool.
