### ISSUE TITLE
HP not showing models for Windows 10 22H2

### ISSUE THREAD

**Issue by mug8pm** [maurice-daly/DriverAutomationTool#439]
Hi,

We are preparing for the upgrade to Windows 10 22H2, we are trying to find driver packages for our HP models is not working as there are no models found. I checked the HP website (https://hpia.hpcloud.hp.com/downloads/driverpackcatalog/HP_Driverpack_Matrix_x64.html) and there are packages available for Windows 10 22H2.

Microsoft is not showing info as well, Lenovo is showing models.

**Comment by korpx** [comment]
Do you get any results choosing an earlier release like 21H2 or 21H1?
We are looking for drivers for "HP ProBook 440 G9 Notebook PC" and get no results for any of the Windows 10 versions.

It's in the matrix at https://hpia.hpcloud.hp.com/downloads/driverpackcatalog/HP_Driverpack_Matrix_x64.html#:~:text=HP%20ProBook%20440%2014%20inch%20G9%20Notebook%20PC

The CVA lists;
[Operating Systems]
WT64_21H2=OEM
WT64_21H1=OEM
WT64_20H2=OEM

**Comment by mug8pm** [comment]
Yes, older versions are showing results, it's 22H2 that is having an issue.

**Comment by mug8pm** [comment]
This problem is solved. I renamed the HP*.xml files in the .\MSEndpointMgr\Driver Automation Tool\Temp folder, restarted the tool and now a fresh (and updated) version of the xml files is downloaded. For some reason these files are not updating.
