### ISSUE TITLE
Windows 11 Lenovo Driver Imports not working, MDT or Download

### ISSUE THREAD

**Issue by GitEvanH123** [maurice-daly/DriverAutomationTool#442]
It seems like Lenovo models seem to have issues with downloads, at least with Windows 11 versions. Program gives no errors, but completes far too quickly, and nothing ends up getting downloaded. This is using Windows Server 2016 if that matters. 

**A peek in the JobSummary.csv gives:**

"Event Generated","Make","Model","OS Selection","Package Type","Version","Action"
"12/21/2022 10:48:52","Lenovo","ThinkPad T16 Gen 1 Type 21BV 21BW","Windows 11","DRIVER","202207","[Error] - OS support not found"
"12/21/2022 10:48:52","Lenovo","ThinkPad T16 Gen 1 Type 21CH 21CJ","Windows 11","DRIVER","202209","[Error] - OS support not found"
"12/21/2022 10:48:52","Lenovo","ThinkPad T14 Gen 3 Type 21AH 21AJ","Windows 11","DRIVER","202207","[Error] - OS support not found"
"12/21/2022 10:48:52","Lenovo","ThinkPad T14 Gen 3 Type 21CF 21CG","Windows 11","DRIVER","202209","[Error] - OS support not found"

**Also found this in the logs after attempting to download both Driver and BIOS, despite not needing BIOS:**

<![LOG[======== Lenovo Download ThinkPad T16 Gen 1 Type 21BV 21BW DRIVER PROCESSING STARTED ========]LOG]!><time="10:51:50.268 -480" date="12-21-2022" component="DriverAutomationTool" context="AD\contoso" type="1" thread="19960" file="">
<![LOG[- Download: Latest driver revision found - 202207]LOG]!><time="10:51:50.283 -480" date="12-21-2022" component="DriverAutomationTool" context="AD\contoso" type="1" thread="19960" file="">
<![LOG[- Adding details to summary output]LOG]!><time="10:51:50.299 -480" date="12-21-2022" component="DriverAutomationTool" context="AD\contoso" type="1" thread="19960" file="">
<![LOG[- Download: New driver package detected - Processing]LOG]!><time="10:51:50.315 -480" date="12-21-2022" component="DriverAutomationTool" context="AD\contoso" type="1" thread="19960" file="">
**<![LOG[- Download: Driver package not found for ThinkPad T16 Gen 1 Type 21BV 21BW running Windows 11 x64. Skipping ThinkPad T16 Gen 1 Type 21BV 21BW]LOG]!><time="10:51:50.330 -480" date="12-21-2022" component="DriverAutomationTool" context="AD\contoso" type="2" thread="19960" file="">**
<![LOG[======== Lenovo Download ThinkPad T16 Gen 1 Type 21BV 21BW DRIVER PROCESSING FINISHED ========]LOG]!><time="10:51:50.349 -480" date="12-21-2022" component="DriverAutomationTool" context="AD\contoso" type="1" thread="19960" file="">

**Comment by Jaekty** [comment]
Same issue here

**Comment by chrisecklar** [comment]
There's a new version of the tool posted, 7.2.2.  I've been having the same issues and downloading the new version resolves some of them.

**Comment by grahampriley** [comment]
We had the same issue and 7.2.2 resolved the issue for us. Bloody Lenovo!

**Comment by GitEvanH123** [comment]
Seems issue is fixed with 7.2.2 update. Tested and confirmed fix.
