### ISSUE TITLE
Incorrect Model Selected Latitude 7520/Precision 7520

### ISSUE THREAD

**Issue by Get-SomeCofee** [maurice-daly/DriverAutomationTool#445]
We have Precision 7520. Not Latitude 7520
Initially the DriverAutomationTool detects this correctly (Image1)
However later it selects/downloads "Dell 7520" and "Precision 7520" (Image 2)
When I look in the readme of the package 7520-Windows10-x64-A09, it states the model as Latitude 7520 (Image3)

Why is this happening?  We have zero Latitude 7520 systems.

Image1
![image](https://user-images.githubusercontent.com/99751000/211620955-9dc92068-de2b-45d2-aaf6-1088a7b378d1.png)

Image2
![image](https://user-images.githubusercontent.com/99751000/211621178-8488ae7d-a68f-482a-9dd4-b530c271dcf6.png)

Image3
![image](https://user-images.githubusercontent.com/99751000/211621931-f79a7fe1-9a9a-469a-8f82-5d0254f9a6ff.png)

Image4
![image](https://user-images.githubusercontent.com/99751000/211622718-a27ee436-b9d4-4b40-aa47-695a7bfdbd7f.png)

**Comment by maurice-daly** [comment]
This was an issue caused by a change in the Dell XML, and this should have been resolved since you posted the issue.
