### ISSUE TITLE
Troubles with DELL

### ISSUE THREAD

**Issue by lukymu** [maurice-daly/DriverAutomationTool#447]
Hello,
I use Driver Automation tool so today I have problem with download of DELL.
It does not download Drivers catalog.
I received this error.
![image](https://user-images.githubusercontent.com/122605294/212292506-5d5115f0-6de6-44a2-9150-1d4531167f3a.png)

Is there exist some solution for fix this problem?

Thank you very much.

Lukas

**Comment by nodiaque** [comment]
started having this problem today, was working fine last week

**Comment by nodiaque** [comment]
Ok I fixed it. Go into msengpointmgr\Driver Automation Tool\Temp\ and delete everything. Launch the software.
