### ISSUE TITLE
Modern Driver Management Package not created in MECM

### ISSUE THREAD

**Issue by mpierce-tamu** [maurice-daly/DriverAutomationTool#453]
I Have installed, uninstalled and installed again several times, but the Modern Driver Management package never gets created.  I Have downloaded the PS script that it's supposed to be associated with, but I thought this package was created by default.  Did I miss a step somewhere?

I'm new to GitHub and your product and didn't know where else to ask this question as I didn't see that you had a forum of any kind.

Kindly point me in the right direction.  Thanks.
-matt

**Comment by aarnold-sd68** [comment]
You need to create the script package yourself if I remember correctly.  The only part that is automatic is the drivers themselves and even that is based on the setting you give it.  https://msendpointmgr.com/modern-driver-management/ step 4 is the step you missed.

**Comment by mpierce-tamu** [comment]
Thanks.  Somehow, I thought that step was created via the application install and placed into the MECM Database.  I re-read all steps again and I believe I have that part ironed out now.  I Have a new issue, but will create a new issue instance for it for tracking purposes.  Thanks.
-matt
