### ISSUE TITLE
The UNC pathes you have specified currently exceed 50 characters in length

### ISSUE THREAD

**Issue by kasparssc** [maurice-daly/DriverAutomationTool#461]
For half a year I start seeing that I cannot download any Lenovo driver. Log complains about 50 characters.
I tried Windows 10 21H2 or 22H2 None worked. I have 7.2.1. I think version prior 7.0.0 was not such issue ( I could be wrong).
It also does not help if I download package manually and extract it. Package in MECM is not created.
In log you can see that there is newer driver but tool is not downloading and processing it.
What I am doing wrong?
**********************
======== Starting Download Processes ========	 	 
- Models selected: Lenovo ThinkPad P14S Gen 3 Type 21J5 21J6	 	 
- Operating System specified: Windows 10	 	 
- Operating System architecture specified: x64	 	 
- Site Code specified: TTT	 	 
- Download Path specified: \\servername\share$\Deployment\Source\Drivers	 	 
- Package Path specified: \\servername\share$\Deployment\Packages\Drivers	 	 
- Windows 10 build 10.0.19045.1 and version 22H2 identified for driver match	 	 
======== Processing Lenovo ThinkPad P14S Gen 3 Type 21J5 21J6 Downloads ========	 	 
- Starting Download, extract and import processes for Lenovo model: ThinkPad P14S Gen 3 Type 21J5 21J6	 	 
- Setting Lenovo variables	 	 
- Lenovo ThinkPad P14S Gen 3 Type 21J5 21J6 matching model type: 21J6 21J5	 	 
- Looking up version based on 22H2 and OS based on Windows 10	 	 
- Driver Download is https://download.lenovo.com/pccbbs/mobiles/tp_t14-p14s_gen_3-t16-p16s_gen_1_amd_mt21cf-21cg-21j5-21j6-21ch-21cj-21ck-21cl_w1064_202209.exe and type is Drivers	 	 
- Driver package URL - https://download.lenovo.com/pccbbs/mobiles/tp_t14-p14s_gen_3-t16-p16s_gen_1_amd_mt21cf-21cg-21j5-21j6-21ch-21cj-21ck-21cl_w1064_202209.exe	 	 
- Using Configuration Manager console BIOS package folder - TTT:\Package\BIOS Packages\Lenovo	 	 
- Using Configuration Manager console Driver package folder - TTT:\Package\Driver Packages\Lenovo	 	 
- Driver extract location set - \\servername\share$\Deployment\Source\Drivers\Lenovo\ThinkPad P14S Gen 3 Type 21J5 21J6\Windows10-22H2-x64-202209	 	 
- Driver package location set - \\servername\share$\Deployment\Packages\Drivers\Lenovo\ThinkPad P14S Gen 3 Type 21J5 21J6\Windows10-22H2-x64-202209	 	 
Warning: The UNC pathes you have specified currently exceed 50 characters in length. This can cause issues during the driver extract phase. If you have issues, creating a new share so only the server and base share names are used.	 	 
======== Lenovo ConfigMgr ThinkPad P14S Gen 3 Type 21J5 21J6 DRIVER PROCESSING STARTED ========	 	 
- ConfigMgr: Latest driver revision found - 202209	 	 
- ConfigMgr: Checking ConfigMgr for driver packages matching - Drivers - Lenovo ThinkPad P14S Gen 3 Type 21J5 21J6 - Windows 10 22H2 x64	 	 
- Adding details to summary output	 	 
- ConfigMgr: New driver package detected - Processing	
- **Always see next line - package not found** 	 
- ConfigMgr: Driver package not found for ThinkPad P14S Gen 3 Type 21J5 21J6 running Windows 10 x64. Skipping ThinkPad P14S Gen 3 Type 21J5 21J6	 	 
======== Lenovo ConfigMgr ThinkPad P14S Gen 3 Type 21J5 21J6 DRIVER PROCESSING FINISHED ========	 	 
======== Superseded Driver Package Option Processing ========	 	 
======== Superseded BIOS Package Option Processing ========	 	 
- Remaining models to process: 0	 	 
======== PROCESS SUMMARY ========	 	 
- Added / updated 0 BIOS packages	 	 
- Added / updated 1 Driver packages	 	 
- Full details available here: D:\Program Files\MSEndpointMgr\Driver Automation Tool\Logs\JobSummary.csv	 	 
======== FINISHED PROCESSING ========

**Comment by aarnold-sd68** [comment]
I would try what it says to do.  "Warning: The UNC paths you have specified currently exceed 50 characters in length. This can cause issues during the driver extract phase. If you have issues, creating a new share so only the server and base share names are used."  You may also try upgrading the Task sequence script to the latest, but that has caused problems from me and other with regards to the TargetOSname variable, it doesn't like the spaces.

**Comment by kasparssc** [comment]
What changed that system/tool do not understand this path anymore? Last year in december it worked.
Drivers\Lenovo\ThinkPad P14S Gen 3 Type 21J5 21J6\Windows10-22H2-x64-202209 is allready 78 characters
Windows understand 256 characters.
I do not know what to shorten. I can only shorten "drivers\lenovo" but than it starts to look very manual to download for each manufacturer to different share or manualy moving around downloaded files.

**Comment by HermanGB** [comment]
I do all processing locally on the server and have set **"D:\DAT"** as download location. 
After the download and extraction process is done, the files are copied to the appropriate share for further processing into ConfigMgr.

**Comment by aarnold-sd68** [comment]
Yeah mine is a little bigger T:\DriverDownload but I do the same, do it all on my main sccm server.  It's not perfect but it works.

**Comment by kasparssc** [comment]
Thanks I managed to change both locations to drive:\folder Error 50 character went away.
Why it worked in previous tool versions? Only two last versions showed this.
Now is more manual worked involved.
Offtopic: And I upgraded only because I need Windows 10 22H2 which is by the way is not working also (tool shows that driver is available, but Lenovo does not have it, it has Win11 22H2)
