### ISSUE TITLE
Version 7.2.2 Cant find 22h2 drivers from Microsoft

### ISSUE THREAD

**Issue by Pelle1974** [maurice-daly/DriverAutomationTool#463]
From the Processlog it tries to filter models based on build 21621 when it should filter on 22621
It´s the same for both win10 and win 11

======== Querying Model List(s) ========	DriverAutomationTool	2023-02-22 10:27:26	12240 (0x2FD0)
- Reading Microsoft JSON Web content from https://raw.githubusercontent.com/maurice-daly/DriverAutomationTool/master/Data/OSDCatalogMicrosoftDriverPack.json	DriverAutomationTool	2023-02-22 10:27:28	12240 (0x2FD0)
- Reading Driver Pack URL - https://raw.githubusercontent.com/maurice-daly/DriverAutomationTool/master/Data/OSDCatalogMicrosoftDriverPack.json	DriverAutomationTool	2023-02-22 10:27:28	12240 (0x2FD0)
- Filtering models based on Windows 11 build 21621	DriverAutomationTool	2023-02-22 10:27:28	12240 (0x2FD0)
- No Microsoft models Found. If you are using a proxy server please specify the proxy in the Proxy Server Settings tab	DriverAutomationTool	2023-02-22 10:27:28	12240 (0x2FD0)

**Comment by HeyZeus-Tech** [comment]
@maurice-daly  is there an ETA on updating the catalog for MS devices?
URLs for Surface Laptop Studio for Windows 10/11 22H2:
https://download.microsoft.com/download/b/3/0/b30ecc34-3bab-4c68-a5b3-0d258d73e747/SurfaceLaptopStudio_Win11_22000_22.114.42841.0.msi
https://download.microsoft.com/download/b/3/0/b30ecc34-3bab-4c68-a5b3-0d258d73e747/SurfaceLaptopStudio_Win10_19042_22.114.42840.0.msi

**Comment by AkosBakos** [comment]
You have to choose Windows 11 from the dropdown.
The JSON file is already correct: https://raw.githubusercontent.com/maurice-daly/DriverAutomationTool/master/Data/OSDCatalogMicrosoftDriverPack.json
![2](https://user-images.githubusercontent.com/44706641/225888111-75cefe9b-486e-4e97-8ea5-27c554a19775.jpg)
