### ISSUE TITLE
Modern Driver Management 6.4.8 setting not saving

### ISSUE THREAD

**Issue by nitndar** [maurice-daly/DriverAutomationTool#49]
In MDM 6.4.8 proxy or any other setting is not getting saved.

**Comment by chaosisbliss** [comment]
I can confirm settings are not saving once closing the applications. I am using the .exe as well.

**Comment by chaosisbliss** [comment]
I removed the older .MSI installed version from Program and Features and then ran the .MSI in the downloaded 6.4.8 version.  I After installing, I made some changes to settings and closed the application and relaunched using the installed version not the .exe. I can confirm the settings are now saving.

**Comment by maurice-daly** [comment]
There was an issue where some of the UI elements became unlinked from underlying actions. This has been fixed in 6.4.9.
