### ISSUE TITLE
Which is the right repository?

### ISSUE THREAD

**Issue by Get-SomeCofee** [maurice-daly/DriverAutomationTool#502]
Which is the right repository?

https://github.com/maurice-daly/DriverAutomationTool
or
https://github.com/MSEndpointMgr/ModernDriverManagement

The first one seems to be updated more often, but the second one is the one linked on https://msendpointmgr.com/modern-driver-management/  Users and support are split.  This is confusing.

**Comment by sveken** [comment]
https://github.com/maurice-daly/DriverAutomationTool is the new home
