### ISSUE TITLE
Unable to download driver for Dell Precision 3660 Tower

### ISSUE THREAD

**Issue by Get-SomeCofee** [maurice-daly/DriverAutomationTool#503]
404 - File or directory not found.
https://downloads.dell.com/FOLDER10580011M/1/Precision-3660-Tower-70RVX_Win10_1.0_A07.exe

`- Windows 10 identified for driver match	DriverAutomationTool	9/15/2023 5:12:19 PM	25784 (0x64B8)
======== Processing Dell Precision 3660 Tower Downloads ========	DriverAutomationTool	9/15/2023 5:12:19 PM	25784 (0x64B8)
- Starting Download, extract and import processes for Dell model: Precision 3660 Tower	DriverAutomationTool	9/15/2023 5:12:19 PM	25784 (0x64B8)
- Setting Dell variables	DriverAutomationTool	9/15/2023 5:12:19 PM	25784 (0x64B8)
- Using SKU : 0A9F	DriverAutomationTool	9/15/2023 5:12:19 PM	25784 (0x64B8)
- Dell System Model ID is : 0A9F;0AA0	DriverAutomationTool	9/15/2023 5:12:19 PM	25784 (0x64B8)
- Using Configuration Manager console BIOS package folder - XXX:\Package\BIOS Packages\Dell	DriverAutomationTool	9/15/2023 5:12:27 PM	25784 (0x64B8)
- Using Configuration Manager console Driver package folder - XXX:\Package\Driver Packages\Dell	DriverAutomationTool	9/15/2023 5:12:27 PM	25784 (0x64B8)
======== Dell Precision 3660 Tower BIOS PROCESSING STARTED ========	DriverAutomationTool	9/15/2023 5:12:27 PM	25784 (0x64B8)
- Reading Dell product XML file - C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\CatalogPC.xml	DriverAutomationTool	9/15/2023 5:12:27 PM	25784 (0x64B8)
- Attempting to match based on multiple model package	DriverAutomationTool	9/15/2023 5:12:28 PM	25784 (0x64B8)
- Found BIOS URL FOLDER10359138M/1/Precision_3660_2.7.0.exe	DriverAutomationTool	9/15/2023 5:12:28 PM	25784 (0x64B8)
- Latest available BIOS version from OEM is 2.7.0	DriverAutomationTool	9/15/2023 5:12:28 PM	25784 (0x64B8)
- Checking ConfigMgr for existing BIOS entries, and obtaining latest	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- Latest version from ConfigMgr is 2.7.0	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- Comparing BIOS versions	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- Using new Dell versioning for BIOS matching	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- BIOS package already exists for Dell Precision 3660 Tower (Version 2.7.0).	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- Current BIOS package is already up to date - BIOS Update - Dell Precision 3660 Tower - 2.7.0 (XXX00582)	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
======== Dell Precision 3660 Tower BIOS PROCESSING FINISHED ========	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
======== Dell ConfigMgr Precision 3660 Tower DRIVER PROCESSING STARTED ========	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- ConfigMgr: Latest driver revision found - A07	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- ConfigMgr: Checking ConfigMgr for driver packages matching - Drivers - Dell Precision 3660 Tower - Windows 10 x64	DriverAutomationTool	9/15/2023 5:12:29 PM	25784 (0x64B8)
- Adding details to summary output	DriverAutomationTool	9/15/2023 5:12:30 PM	25784 (0x64B8)
- ConfigMgr: New driver package detected - Processing	DriverAutomationTool	9/15/2023 5:12:30 PM	25784 (0x64B8)
- ConfigMgr: Creating Precision 3660 Tower download folder	DriverAutomationTool	9/15/2023 5:12:30 PM	25784 (0x64B8)
- ConfigMgr: Downloading Precision-3660-Tower-70RVX_Win10_1.0_A07.exe	DriverAutomationTool	9/15/2023 5:12:30 PM	25784 (0x64B8)
- ConfigMgr: Downloading from URL: https://downloads.dell.com/FOLDER10580011M/1/Precision-3660-Tower-70RVX_Win10_1.0_A07.exe	DriverAutomationTool	9/15/2023 5:12:30 PM	25784 (0x64B8)
- BitsTransfer: Checking BITS background job	DriverAutomationTool	9/15/2023 5:12:35 PM	25784 (0x64B8)
- BitTransfer: Job state is "Error Error Error"	DriverAutomationTool	9/15/2023 5:12:35 PM	25784 (0x64B8)

`

**Comment by tunnelofsludge** [comment]
Having the same issue as well.

**Comment by Get-SomeCofee** [comment]
Opened case with Dell.  Dell fixed the bad link.
