### ISSUE TITLE
Windows 11 23H2

### ISSUE THREAD

**Issue by FredrikMatt** [maurice-daly/DriverAutomationTool#514]
Hi!

Can we expect Windows 11 23H2 support to arrive soon?

**Comment by stephannn** [comment]
I think at first eg. HP has to update their catalogue:
https://ftp.hp.com/pub/caps-softpaq/cmit/HPClientDriverPackCatalogUpdateInfo.xml
there is still no information about 23H2 in

**Comment by FredrikMatt** [comment]
I just looked here: https://hpia.hpcloud.hp.com/downloads/driverpackcatalog/HP_Driverpack_Matrix_x64.html

**Comment by stephannn** [comment]
I see.
I just added 23H2 but could not test it yet:
https://github.com/stephannn/DriverAutomationTool/blob/master/Current%20Branch/7.2.2/DriverAutomationTool.ps1

**Comment by FredrikMatt** [comment]
Thanks. I can see the powershell script, but im not sure I understand. There will be a new .EXE file for the application when you tested 23H2?

**Comment by stephannn** [comment]
The exe is just the PowerShell script, just in a wrapper and there I am not the developer of this app, no ;)
However, yesterday I tried some driver packages and it seems to be working. BIOS on the other hand only works with 22H2. I have to investigate if I find some time.

**Comment by NightSwimming** [comment]
Hi Maurice,

Can you please let us know if we can expect Windows 11 23H2 support to arrive soon?

**Comment by maurice-daly** [comment]
All,

Sorry for the delay in my responses. I have been super busy with work and trying to balance family life. The Windows 11 23H2 update will be out by the end of the week. 

Maurice

**Comment by maurice-daly** [comment]
I've hit a bit of a bump in the road with this as the sources I was using from HP and Lenovo are not showing 23H2 in their catalog files. I'm working on it.

**Comment by ajn142attamu** [comment]
Looks like Lenovo is adding 23H2 drivers, even if they aren't labelling them as such yet.

![image](https://github.com/maurice-daly/DriverAutomationTool/assets/87684829/44024a84-e082-4d47-ab84-b266a25c6f2d)

**Comment by ajn142attamu** [comment]
HP, on the other hand, hasn't updated the driver catalog since September of last year.

![image](https://github.com/maurice-daly/DriverAutomationTool/assets/87684829/2e960d11-9c12-4f4a-81bf-01e62058d744)

**Comment by kuraimistral** [comment]
@maurice-daly 
I think they moved cabs:
XMLCabinetSource = https://hpia.hpcloud.hp.com/downloads/driverpackcatalog/HPClientDriverPackCatalog.cab
PlatFormList = https://hpia.hpcloud.hp.com/ref/platformList.cab

**Comment by maurice-daly** [comment]
Support has been added in the latest build
