### ISSUE TITLE
Lenovo ThinkPad P1 Gen 6 Type 21FV 21FW - Windows 11 22H2 x64 Model not avalable

### ISSUE THREAD

**Issue by shindesganesh** [maurice-daly/DriverAutomationTool#526]
Lenovo ThinkPad P1 Gen 6 Type 21FV 21FW - Windows 11 22H2 x64 Model is not avalable in new release of MSI.

**Comment by ajn142attamu** [comment]
I'm not seeing this model in the Lenovo-provided XML file that DAT parses to get its model list. This doesn't appear to be an issue with DAT, but with the data Lenovo is providing.

**Comment by ajn142attamu** [comment]
I apologize, I was wrong. Latest copy of the XML pulled from Lenovo's site clearly shows the model, it was missing from my local copy of the XML. Here's how I fixed this issue in my local install:

1. Close DAT
2. Open `C:\Program Files\MSEndpointMgr\Driver Automation Tool\Settings`.
3. Delete OEMLinks.xml.
4. Open `C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp`
5. Delete everything in this folder.
6. Rerun DAT (it will pull the latest copy of OEMLinks.xml from the repo, then pull the latest copy of Lenovo's XML based on that)
7. You should be able to find the package now.

![image](https://github.com/maurice-daly/DriverAutomationTool/assets/87684829/96beb37d-1010-464f-bcc6-9882ce42b82a)

**Comment by shindesganesh** [comment]
Thank you for the quick help . Now its showing me the Gen 6 Model.
