### ISSUE TITLE
Admin Rights + Internet Access Requirements - Not Best Practice

### ISSUE THREAD

**Issue by MikhailCompo** [maurice-daly/DriverAutomationTool#53]
The application must be run with admin rights. The application typically needs to connect to the internet. This combination elevates risk any may be unnecessary.

One reason for requiring admin rights, is that user modifiable data exists in Program Files, which goes against best practice. Better locations would be %AppData% or  %ProgramData%.

Request that the requirement for the application to *run* with admin rights is removed.

**Comment by maurice-daly** [comment]
The tool can be run remotely from the site server, as long as sufficient rights to configuration manager are provisioned to the running account. The reason for installing into Program Files is to adhere to defaults within app control mechanisms like app locker, and given if the app is installed on a server, that the settings could be persisted across multiple users (yes it could be written to the all users profile too).
