### ISSUE TITLE
Driver Automation Tool.msi SHA256 not matching

### ISSUE THREAD

**Issue by screamtracker** [maurice-daly/DriverAutomationTool#546]
get-filehash -Path 'c:\temp\Driver Automation Tool.msi' -Algorithm SHA256

Algorithm       Hash
SHA256          C40B3E543A4CA61508D6370DB285BB7A468985A7AEF3F3DA02E68C916E1F007E

[MSI SHA 256](https://github.com/maurice-daly/DriverAutomationTool/blob/master/Driver%20Automation%20Tool.msi.sha256)
> 36534002f2f3eeccef53f6ec6d8738a59ca66befb7e45678cd7ff36f385bc6c0

**Comment by osxos** [comment]
I'm getting the correct hash via 7Zip from the [master.](https://github.com/maurice-daly/DriverAutomationTool/blob/master/Driver%20Automation%20Tool.msi)

**Comment by screamtracker** [comment]
As am I. TIL thanks!
