### ISSUE TITLE
Get-CMDriverPackage: A Parameter cannot be found

### ISSUE THREAD

**Issue by dsolodow** [maurice-daly/DriverAutomationTool#55]
> Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.
>
>At line:18107 char:95
>+ ... ackage -name "*$Model -*$WindowsVersion*$Architecture*" -Fast | Selec ...
>+                                                             ~~~~~
>    + CategoryInfo          : InvalidArgument: (:) [Get-CMDriverPackage], ParameterBindingException
>    + FullyQualifiedErrorId : >NamedParameterNotFound,Microsoft.ConfigurationManagement.Cmdlets.Osd.Commands.GetDriverPackageCommand

-------
Get-CMDriverPackage doesn't have a -Fast parameter (at least not in CM2002)

**Comment by chaosisbliss** [comment]
I confirmed this is an issue in MEMCM 2002. I just updated the line to remove the -Fast option only. The -Fast is available for get-cmpackage. 

Thanks for the hard work on this!!!!

**Comment by cmacnichol** [comment]
Same issue with MECM 1910 and Version 6.4.8.

Removed the -Fast parameter from Lines 15380 and 15395.  Think I missed a line though. Cause I do not have the line it is referencing in the error.

**Comment by eethball** [comment]
I'm also having this issue, however even if I remove the "-Fast" parameter from the lines mentioned by Chris, the errors still show up in window.

**Comment by roman-za** [comment]
When I want to process drivers for Latitude 5400, I got  same error. runnig exe file ver 6.4.8 hotfix3
Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.
At line:**18124** char:95
+ ... ackage -name "*$Model -*$WindowsVersion*$Architecture*" -Fast | Selec ...

When  I remove the '- Fast' parameter on line 15380, it has not effect and the same error reappears. (PS script DriverAutomationTool.ps1 from 6.4.8 version).

The same tested with file DriverAutomationTool.exe ver 6.4.9 BETA I got almost the same error, only different line.
Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.
At line:**18098** char:97
+ ... ackage -name "*$Model -*$WindowsVersion*$Architecture*" -Fast | Selec ...

Please help or fix the DriverAutomationTool.exe file

running on MECM ver 2002

**Comment by roman-za** [comment]
The same tested with file DriverAutomationTool.exe ver 6.4.9 BETA (File size 2612 KB) I got almost the same error, only different line.
Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.
At line:**18140** char:97

... ackage -name "$Model -$WindowsVersion*$Architecture*" -Fast | Selec ...

**Comment by Staja** [comment]
6.4.8
`Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.`
`At line:18124 char:95`
`+ ... ackage -name "*$Model -*$WindowsVersion*$Architecture*" -Fast | Selec ...`
`+                                                             ~~~~~`
`    + CategoryInfo          : InvalidArgument: (:) [Get-CMDriverPackage], ParameterBindingException`
`    + FullyQualifiedErrorId :` `NamedParameterNotFound,Microsoft.ConfigurationManagement.Cmdlets.Osd.Commands.GetDriverPackageCommand`

**Comment by ronmanp** [comment]
Same issue here on MEMCM 1910 with DAT 6.4.8

**Comment by roman-za** [comment]
This issue was partially solved by version 6.4.9 hotfix (DriverAutomationTool.exe file size 2627KB) 
Creating Standard package without issue.
Creating Driver package - Error The SMS Provider reported an error. (without details in verbose window)
Tested on Dell Latitude 5400 drivers.

**Comment by maurice-daly** [comment]
Please raise this issue in the MSEndpointMgr github repo
