### ISSUE TITLE
New HP Model (elitebook 660 G11) not found

### ISSUE THREAD

**Issue by Shkelton** [maurice-daly/DriverAutomationTool#551]
Hello, I am new to using this tool so probably an easy fix/process that I need to follow.

We ordered new HP Elitebook 660 G11 laptops. In preparation for these I am trying to create the driver packages, but no matter what I do from the various OS selections the tool never finds anything with 660 in it. And only finds one device that is a G11. How do I get the tool to reach out to HP and get a current list of devices to populate? I read through the documentation and only found a section on adding unknow classes in Configmanager but this is for modern driver management.

Screenshot below

![Capture](https://github.com/user-attachments/assets/443a74ca-3367-4474-875b-9453a46ecf38)

If I could be pointed in the right direction - I would appreciate it

thank you

**Comment by MichielSegers-Cronos** [comment]
Same issue here

**Comment by WeXT15** [comment]
Same here

**Comment by Shkelton** [comment]
I am pinging in here once more in the hopes that someone may have a fix/work around for this?

Thank you

**Comment by THH-TC** [comment]
Found this same issue today for drivers for a 630 G11 - It looks like HP changed the location for the XML file, and have just abandoned the old one.

I found the new link in the OEMLinks.xml file in this Project, so it looks like we just need an update to the tool to use the new URL.
link here in case this has changed for other vendors:
https://github.com/maurice-daly/DriverAutomationTool/blob/master/Data/OEMLinks.xml

For a temporary work around:
> Take a backup of your 'Driver Automation Tool\Temp' folder
> Download the new file .cab file from https://hpia.hpcloud.hp.com/downloads/driverpackcatalog/HPClientDriverPackCatalog.cab
> Copy the cab file into your 'Driver Automation Tool\Temp' folder
> Extract the Cab file in this folder, overwriting the existing HPClientDriverPackCatalog.xml file
> Start the tool and the new models should all be present

I can't say if older models will still be present, so you may need to switch your xml files back and forth as needed

**Comment by Shkelton** [comment]
Hello there. Thank you for the update. I actually went and started the process for the work around that you described above. However running the tool a bunch of new HP devices populated that were not there before - including the 660. So no work around needed. I assume that an update was introduced either in the tool or HP updated on their end. In either case it is working and thank you for the efforts to get it there.
