### ISSUE TITLE
Lenovo Model Detection not working

### ISSUE THREAD

**Issue by woodgre** [maurice-daly/DriverAutomationTool#56]
Sure it's related to the new XML catalog and their massive schema change.

**Comment by woodgre** [comment]
The function Find-LenovoModelType has a parameter that the detection uses called $ModelType, but all of the code that parses the ModelType is commented out, and is using syntax from the old schema.

I changed the function closer to what used to be there and it works:

`		if ($Model.Length -gt 0) {
			$global:LenovoModelType = ($global:LenovoModelDrivers | Where-Object {
					$_.name -eq $Model
				}).Types.Type
		}
		if ($ModelType.Length -gt 0) {
			$global:LenovoModelType = ($global:LenovoModelDrivers | Where-Object {
					($_.Types | Select-Object -ExpandProperty Type) -match $ModelType
				}).Name | Select-Object -first 1
		}

		Return $global:LenovoModelType `

**Comment by surt-it** [comment]
Hi..
Lenovo Model Detection not working to Windows 2004 but work to windows 1909

**Comment by woodgre** [comment]
That's a problem with Lenovo's XML file.  They are tagging their 2004 releases as 1909, so it will have to be fixed by them.

**Comment by teh1tn1nj4** [comment]
What is your full function?  I can't get it working at all, even with dropping in your code above.

**Comment by maurice-daly** [comment]
Model detection logic overhauled in the latest release.
