### ISSUE TITLE
Surface Go 2 1901 not picking up driver package

### ISSUE THREAD

**Issue by simulacra75** [maurice-daly/DriverAutomationTool#57]
Have downloaded and distributed all available Surface Go packages but none of them appear to be "applicable" to the device i am trying to image. 

Below is snippet from the ApplyDriverPackage.log

[ApplyDriverPackage]: Apply Driver Package process initiated
 - Apply driver package deployment type: PreCache
 - Apply driver package operational mode: Production
[PrerequisiteChecker]: Starting environment prerequisite checker
 - Supported computer platform detected, script execution allowed to continue
 - Computer manufacturer determined as: Microsoft
 - Computer model determined as: Surface Go 2
 - Computer SystemSKU determined as: Surface_Go_2_1901
 - Computer model detection was successful
 - Computer SystemSKU detection was successful
 - Computer details successfully verified
 - Determined primary computer detection method: SystemSKU
....
[WebService]: Starting ConfigMgr WebService phase
 - Successfully connected to ConfigMgr WebService at URI: http://XXX.XXX.XXX/ConfigMgrWebService/ConfigMgr.asmx
 - Retrieved a total of '94' driver packages from web service matching operational mode: Production
 - Attempting to detect OS Image data from task sequence with PackageID: XXX00009
 - Multiple OS Image objects detected and OSImageTSVariableName was not specified. Selecting the first OS Image object from web service call
 - Target operating system name detected as: Windows 10
 - Target operating system architecture detected as: x64
 - Target operating system build version detected as: 10.0.18362.836
 - Target operating system translated version detected as: 1903
[WebService]: Completed ConfigMgr WebService phase

....
....

[DriverPackage]: Starting driver package matching phase
 - Initial count of driver packages before starting filtering process: 94
 - Filtering driver package results to detected computer manufacturer: Microsoft
 - Count of driver packages after filter processing: 7
 - Filtering driver package results to only include packages that have details added to the description field
 - Count of driver packages after filter processing: 7
[DriverPackage:XXX0016D]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Go - Windows 10 1903 x64
[DriverPackage:XXX00166]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Go LTE - Windows 10 1903 x64
[DriverPackage:XXX00167]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Laptop 2 - Windows 10 1903 x64
[DriverPackage:XXX00099]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Pro 6 - Windows 10 1903 x64
[DriverPackage:XXX00139]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Pro 6 - Windows 10 1909 x64
[DriverPackage:XXX00163]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Pro 7 - Windows 10 1903 x64
[DriverPackage:XXX0013A]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Pro 7 - Windows 10 1909 x64
[DriverPackage]: Completed driver package matching phase
[DriverPackageValidation]: Starting driver package validation phase
 - Amount of driver packages detected by validation process: 0
 - Validation failed with empty list of matched driver packages, script execution will be terminated
[ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages

**Comment by maurice-daly** [comment]
The Microsoft XML has been updated this morning. Please note that due to the fact build compatibility would need to be checked manually, drivers might not be found against every build for all models. In an update to the DAT, an output will inform you if the driver cant be found in a more friendly manner. Update should be posted later today.

**Comment by azulol** [comment]
I got the same error as @simulacra75 when reinstalling a surface book 2 15 inch with version 3.1.0 of the Script.
In the task sequence i call the script and in the parameter section i write this: 
-URI "http://sdfsdfsdfsdfdf.eu/ConfigMgrWebService/ConfigMgr.asmx" -SecretKey "123456789" -Filter "Drivers" -TargetOSVersion 18363
We are installing Windows 10 Version 20H2, but the rest of our deployments with lenovo devices are working with this parameter.

Do you have a solution for this?
