### ISSUE TITLE
6.4.8 - Loading BitsTransfer module - Mixed mode assembly is built against version 'v2.0.50727' of the runtime 

### ISSUE THREAD

**Issue by GbCaa** [maurice-daly/DriverAutomationTool#58]
This occurs when launching from the start-menu. Later when trying to download you get an error: The 'Get-BitsTransfer' command was found in the module 'BitsTransfer', but the module could not be loaded. For more information, run 'Import-Module BitsTransfer'.

Complete error during loading:

```
Loading` 'FormatsToProcess' from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\BitsTransfer.Format.ps1xml'.
Import-Module : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
At line:162 char:1
+ Import-Module -Name BitsTransfer -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : `FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

This is on Server 2012 R2 running Powershell 5.1 with the .NET Framework 4.5.2. 

If I open Powershell as admin and run DriverAutomationTool.ps1, there are no errors.

**Comment by keniem** [comment]
I noticed this too with Server 2012 R2 & PS 5.1 and latest .NET framework. It's caused by a missing configuration file from DAT installation folder. Bug in DAT installer because it's not adding this file. Just add this file manully to same folder where DriverAutomationTool.exe is located and it should work:

https://github.com/maurice-daly/DriverAutomationTool/blob/master/Content/DriverAutomationTool.exe.config

**Comment by Wav3** [comment]
> 
> 
> I also noticed this today when I was testing new DAT version. It's caused by a missing configuration file from DAT installation folder. This seems to be a bug in DAT installer because it's not creating this file. Just add this file manully to same folder where DriverAutomationTool.exe is located and it should work:
> 
> https://github.com/maurice-daly/DriverAutomationTool/blob/master/Content/DriverAutomationTool.exe.config

I can confirm that manually adding the file `DriverAutomationTool.exe.config` from the GitHub repository solve this issue.  

My System:

- Windows Server 2012 R2 (German localization)
- PowerShell 5.1
- .NET Framework 4.7.03062

**Comment by maurice-daly** [comment]
Please make sure the DriverAutomationTool.exe.config is located in the same folder as the exe.
