### ISSUE TITLE
Surface Pro 3 driver does not download

### ISSUE THREAD

**Issue by surt-it** [maurice-daly/DriverAutomationTool#59]
Info: Selecting known model Surface Pro 3		01-01-1601 00:00:00	0 (0x0000)
Info: Selecting known model Surface Pro 4		01-01-1601 00:00:00	0 (0x0000)
Info: Selecting known model Surface Pro 5		01-01-1601 00:00:00	0 (0x0000)
Info: Validating all required selections have been made		01-01-1601 00:00:00	0 (0x0000)
Validation state is True		01-01-1601 00:00:00	0 (0x0000)
Info: Importing Into Products: ConfigMgr - Standard Pkg		01-01-1601 00:00:00	0 (0x0000)
Info: Download Type: Drivers		01-01-1601 00:00:00	0 (0x0000)
Pre-Check: Download path set To \\server\source$\OSD\Drivere 2\Temp		01-01-1601 00:00:00	0 (0x0000)
======== Starting Download Processes ========		01-01-1601 00:00:00	0 (0x0000)
Info: Models selected: Microsoft Surface Pro 3		01-01-1601 00:00:00	0 (0x0000)
Info: Operating System specified: Windows 10		01-01-1601 00:00:00	0 (0x0000)
Info: Operating System architecture specified: x64		01-01-1601 00:00:00	0 (0x0000)
Info: Site Code specified: P03		01-01-1601 00:00:00	0 (0x0000)
Info: Download Path specified: \\server\source$\OSD\Drivere 2\Temp		01-01-1601 00:00:00	0 (0x0000)
Info: Package Path specified: \\server\source$\OSD\Drivere 2		01-01-1601 00:00:00	0 (0x0000)
Info: Windows 10 build lookup required		01-01-1601 00:00:00	0 (0x0000)
Info: Windows 10 build 10.0.19041.1 and version 2004 identified for driver match		01-01-1601 00:00:00	0 (0x0000)
======== Processing Microsoft Surface Pro 3 Downloads ========		01-01-1601 00:00:00	0 (0x0000)
Info: Starting Download, extract and import processes for Microsoft model: Surface Pro 3		01-01-1601 00:00:00	0 (0x0000)
Info: Setting Microsoft variables		01-01-1601 00:00:00	0 (0x0000)
Info: Atteming match for SurfacePro3		01-01-1601 00:00:00	0 (0x0000)
Info: Microsoft AKA shortlink URL is https://aka.ms/SurfacePro3/19041		01-01-1601 00:00:00	0 (0x0000)
Info: Microsoft redirected URL discovered is https://www.microsoft.com?ref=aka		01-01-1601 00:00:00	0 (0x0000)
Info: Creating custom package root folder - Drivers\ 		01-01-1601 00:00:00	0 (0x0000)
Info: Creating custom package subfolder - Drivers\2004\ 		01-01-1601 00:00:00	0 (0x0000)
Info: Remaining models to process: 0		01-01-1601 00:00:00	0 (0x0000)
======== FINISHED PROCESSING ========		01-01-1601 00:00:00	0 (0x0000)

**Comment by maurice-daly** [comment]
Windows 10 2004 drivers for the Surface Pro 3 for example is not currently available (https://www.microsoft.com/en-us/download/details.aspx?id=38826). The tool will attempt to discover the AKA redirection URL, but this is depending on availability from MS
