### ISSUE TITLE
Surface Devices - Unable to Match Computer Model

### ISSUE THREAD

**Issue by chaosisbliss** [maurice-daly/DriverAutomationTool#6]
Hi,

First off, I wanted to say thanks for your continued efforts on the DAT as WebService. This has truly been a blessing. 

I seem to be running into a weird issue, that just started, here with the latest updates with Surface devices. I am running WebService 1.7, DAT is 6.4.6, and Invoke-CMApplyDriverPackage is 2.2.7.

We have had a significant increase in use of Surface devices despite advising not to do so. I want get into all of that. As you can see from the Task Sequence Monitor, I am receiving nothing but errors in regards to Surface devices. I have my task sequences separated out based on Laptop/Desktop/Surface so I can monitor them properly.  Oddly enough, all my images are 1909. There are no OS Images for 1903 and have been completely purged from the system. My other Task Sequences detect without any issue for the OS Version. 
![image](https://user-images.githubusercontent.com/51373358/77347790-603c0900-6d06-11ea-9b9c-05f164b6a8c7.png)

I do remember there being an issue where the Driver Package did not match properly in which the package name had to be renamed. I have tried the default donwloaded package for both 1903 and 1903 and renamed them from the Drivers - Microsoft Surface Boo2 - Windows 10 1903 x64 to Surface Book 2 - Windows 10 1903 x64.
I did notice, in the comment the models included were all set to Surface_Laptop. I attempted to correct this in testing to match, but this did not correct the issue. 
![image](https://user-images.githubusercontent.com/51373358/77348334-451dc900-6d07-11ea-81b4-89b6b60f6144.png)
![image](https://user-images.githubusercontent.com/51373358/77348425-70081d00-6d07-11ea-8897-c5ad180066a7.png)

I've attached a few logs that indicate a driver was not found. 
[ApplyDriverPackage.log](https://github.com/maurice-daly/DriverAutomationTool/files/4371117/ApplyDriverPackage.log)
[ApplyDriverPackage.log](https://github.com/maurice-daly/DriverAutomationTool/files/4371118/ApplyDriverPackage.log)

I am not sure what else to test. Any guidance would be greatly appreciate it.

**Comment by agressiv** [comment]
The problem lies here, the Source XML has wrong SKU to device mapping:

https://www.scconfigmgr.com/wp-content/uploads/xml/MSProducts.xml

Here are the wrong ones:
```
<Model SystemSKU="Surface_Book_2_1832, Surface_Book_2_1793" ProductName="SurfaceBook" DisplayName="Surface Book"></Model>
<Model SystemSKU="Surface_Laptop" ProductName="SurfaceBook2" DisplayName="Surface Book 2"></Model>	
<Model SystemSKU="Surface_Laptop_2_1769_Commercial, Surface_Laptop_2_1769_Consumer" ProductName="SurfaceLaptop" DisplayName="Surface Laptop"></Model>
<Model SystemSKU="Surface_Go_1824_Consumer, Surface_Go_1824_Commercial" ProductName="SurfaceLaptop2" DisplayName="Surface Laptop 2"></Model>
```

Here is what they should be:
```
<Model SystemSKU="Surface_Book" ProductName="SurfaceBook" DisplayName="Surface Book"></Model>
<Model SystemSKU="Surface_Book_2_1832, Surface_Book_2_1793" ProductName="SurfaceBook2" DisplayName="Surface Book 2"></Model>	
<Model SystemSKU="Surface_Laptop" ProductName="SurfaceLaptop" DisplayName="Surface Laptop"></Model>
<Model SystemSKU="Surface_Laptop_2_1769_Commercial, Surface_Laptop_2_1769_Consumer" ProductName="SurfaceLaptop2" DisplayName="Surface Laptop 2"></Model>
```

**Comment by chaosisbliss** [comment]
Great find. I didn't even look there. Do I need to delete the .xml files from the C:\Program Files\SCConfigMgr\Driver Automation Tool\Temp directory to resolve this? Or is the source downloaded from somewhere else?

**Comment by agressiv** [comment]
I've made a few corrections to the above; I simply made my own xml file hosted locally and modified the source until he can fix it, along with the typo fix.

**Comment by chaosisbliss** [comment]
Yeah, you are correct. I corrected the DriverAutomationTool.ps1 Mmodel.SystemSKU to $ModelSystemSKU. I found the Microsoft Variables MicrosoftXMLSource. You just point it to a local file as in "C:\MSProducts.xml". Just making sure I don't mess it up.

**Comment by agressiv** [comment]
With those changes, the model detection is working for me.  I only have access to a single surface device that I can re-image (and that wasn't one of the problem devices) so I have no way of testing an actual image.

**Comment by chaosisbliss** [comment]
I'm good with making the changes you suggested. It's not working as it is now with the typo and the source .xml file. You just created your own MS.XML file and pointed the DriverAutomationTool.ps1 Microsoft variable to a file stored locally on your server? I just need to know if you pointed it like this or something similar?
![image](https://user-images.githubusercontent.com/51373358/78568794-3c89c000-77e8-11ea-9ce2-f6508ebd3b6c.png)

**Comment by agressiv** [comment]
`[xml]$MicrosoftModelXML = (New-Object System.Net.WebClient).DownloadString("$MicrosoftXMLSource")`

It's trying to download the file.  There's a bunch of references to this, doing Invoke-WebRequest, so you'd have to search for all of these and change the logic if you don't have access to a web server.

**Comment by chaosisbliss** [comment]
Ah. That's what I was afraid you would say. Well, thank you for pointing out the issue. I thought it was something on my end. I'll have to wait until he corrects them. Thanks again for your assistance!

**Comment by maurice-daly** [comment]
The Microsoft XML is a manual effort unfortunately. It has however been updated this morning.
