### ISSUE TITLE
Dell Flash Utility won't download

### ISSUE THREAD

**Issue by rtruss** [maurice-daly/DriverAutomationTool#64]
I have confirmed i have the latest flash utility from March 2020 (A04) but the new 6.4.8 version fails to confirm.  Could be that they changed a name of a file on Dells end?  here is from the log: Error: BIOS flash upgrade utility failed to download. Check log for more details.  The tool will find and grab the bios files but cannot create the package as it does not find the flash utility anymore.  Link to current dell flash utility:  https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=wcj0c  notice the zip file name appears to have changed.

**Comment by zebulun78** [comment]
Ditto.

**Comment by cincydash** [comment]
Same

**Comment by nodiaque** [comment]
Fun fact, if you check the temp folder, it's actually downloaded! I just deleted the file and it download it again, but still say the same error (by the way, what log should I check for more details?).

Tried running as admin an didn'T worked.

But, something stranged just happened. I copied over the file in temp to the Flash64Utility on my share. I also selected only 1 device and started download again... and it worked! It said it unzip in the temp folder, then detected a new version, promoted new version and put old in legacy. Everything is created no error, but, when I check in the bios source folder (where SCCM get the package from), it contain the bios files, but not flash utils like the others.

Log file says everything ran fine, but it didn't. While the package is created, it's missing the flash util

`Info: Found BIOS URL FOLDER06279152M/1/Latitude_5X01_Precision_3541_1.9.1.exe	DriverAutomationTool	2020-07-14 08:43:24	78844 (0x133FC)
Info: Latest available BIOS version is 1.9.1	DriverAutomationTool	2020-07-14 08:43:25	78844 (0x133FC)
Info: Checking ConfigMgr for existing BIOS release - 1.9.1	DriverAutomationTool	2020-07-14 08:43:25	78844 (0x133FC)
Info: Comparing BIOS versions	DriverAutomationTool	2020-07-14 08:43:25	78844 (0x133FC)
Info: New BIOS download available	DriverAutomationTool	2020-07-14 08:43:25	78844 (0x133FC)
Info: BIOS Download URL Found: https://downloads.dell.com/FOLDER06279152M/1/Latitude_5X01_Precision_3541_1.9.1.exe	DriverAutomationTool	2020-07-14 08:43:25	78844 (0x133FC)
Info: Downloading Latitude_5X01_Precision_3541_1.9.1.exe BIOS update file	DriverAutomationTool	2020-07-14 08:43:26	78844 (0x133FC)
BitsTransfer: Checking BITS background job	DriverAutomationTool	2020-07-14 08:43:29	78844 (0x133FC)
Info: Downloading Dell flash update utility	DriverAutomationTool	2020-07-14 08:43:30	78844 (0x133FC)
BitsTransfer: Checking BITS background job	DriverAutomationTool	2020-07-14 08:43:31	78844 (0x133FC)
Info: Unzipping latest Dell Flash64 EXE in C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\Flash64W_ZPE.exe	DriverAutomationTool	2020-07-14 08:43:31	78844 (0x133FC)
Info: New Dell Flash 64 EXE version is 	DriverAutomationTool	2020-07-14 08:43:32	78844 (0x133FC)
Info: Latest Dell Flash 64 EXE is 3.3.6	DriverAutomationTool	2020-07-14 08:43:32	78844 (0x133FC)
Info: Creating new/updated Dell Flash 64 source	DriverAutomationTool	2020-07-14 08:43:32	78844 (0x133FC)
Info: Archiving legacy file	DriverAutomationTool	2020-07-14 08:43:32	78844 (0x133FC)
Info: Promoting  release to production	DriverAutomationTool	2020-07-14 08:43:32	78844 (0x133FC)
Info: Copying Dell Flash64Bit EXE To \\server\SCCM_Packages\Drivers\DAT\Dell\Latitude 5401\BIOS\1-9-1\	DriverAutomationTool	2020-07-14 08:43:33	78844 (0x133FC)
ConfigMgr: Creating BIOS Package	DriverAutomationTool	2020-07-14 08:43:33	78844 (0x133FC)
ConfigMgr: Enabling Binary Delta Replication	DriverAutomationTool	2020-07-14 08:43:34	78844 (0x133FC)`

**Comment by nodiaque** [comment]
Ok, I fixed it. The log still say a new version is available and that it's copying it all over the place (which isn't happening), but at least now all packages are created properly.

Get the Flash64W_ZPE.exe from the temp folder and extract it. 
Then copy flash64w.exe to the temp folder.
Next, copy both file to the destination folder (mine is something like share\Dell\FlashUtility)
Start package creation in DAT.

**Comment by maurice-daly** [comment]
Fixed in the latest exe.

**Comment by rtruss** [comment]
Thanks, does that also mean its fixed in the powershell script too?  I do not use the exe as it does not allow me the control I  like for package organization in the MECM console.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
