### ISSUE TITLE
$global:skuValue is null for Lenovo devices

### ISSUE THREAD

**Issue by CharlesNRU** [maurice-daly/DriverAutomationTool#67]
The SKU value is not populated when setting Lenovo variables.
Packages created with version 6.4.8 have nothing in the "Models Included" part of its description.

Quickly looking at the code, I can see that in the function Find-LenovoModelType, a section is commented out which included setting the $global:skuValue

**Comment by maurice-daly** [comment]
Issue fixed. Updated EXE available
