### ISSUE TITLE
6.4.8 crashes after about 30 drivers

### ISSUE THREAD

**Issue by kylelilley** [maurice-daly/DriverAutomationTool#70]
Testing out 6.4.8 and we find it crashes consistently before completion, usually between 30 and 50 driver packages.  Rolling back to 6.4.6 allows to download all 180 packages just fine. 

Any suggestions for troubleshooting?

**Comment by molson98** [comment]
I am also seeing a similar issue. It just sits there frozen and I have to force close.

**Comment by maurice-daly** [comment]
The script is not multithreaded so I can't monitor for hangs unfortunately, and re-writing the entire thing to allow this would be a huge effort.
