### ISSUE TITLE
Lenovo driver downloads still not working.

### ISSUE THREAD

**Issue by geekitup** [maurice-daly/DriverAutomationTool#71]
Lenovo drivers are still broken.  

1. Selecting Windows 10 1909 64bit results in ZERO models being listed.  1903 and 2004 list models fine.  2. If I go to https://support.lenovo.com/us/en/downloads/ds503943 I see there is a driver pack available for 1909 for the model I'm trying to download (M720Q) 
2. If I go to 1903, select the ThinkCentre M720Q then Start Download, it runs for about a second and says processing finished, but actually does not download or process anything.

Running 6.4.8 hotfix version.

`<![LOG[======== Querying Model List(s) ========]LOG]!><time="12:17:07.259 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Warning: No Lenovo models found. If you are using a proxy server please specify the proxy in the Proxy Server Settings tab.]LOG]!><time="12:17:09.290 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="2" thread="9076" file="">
<![LOG[======== Querying Model List(s) ========]LOG]!><time="12:17:14.009 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Found 47 Lenovo model driver packs for Windows 10 2004 64 bit]LOG]!><time="12:17:16.321 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Querying Model List(s) ========]LOG]!><time="12:17:19.384 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Found 47 Lenovo model driver packs for Windows 10 2004 64 bit]LOG]!><time="12:17:21.680 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Querying Model List(s) ========]LOG]!><time="12:17:26.712 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Found 132 Lenovo model driver packs for Windows 10 1903 64 bit]LOG]!><time="12:17:29.633 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Querying Model List(s) ========]LOG]!><time="12:17:32.680 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Found 132 Lenovo model driver packs for Windows 10 1903 64 bit]LOG]!><time="12:17:35.540 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Validating all required selections have been made]LOG]!><time="12:17:40.602 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Validation state is True]LOG]!><time="12:17:40.602 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Importing Into Products: MDT]LOG]!><time="12:17:40.633 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Download Type: Drivers]LOG]!><time="12:17:40.633 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Pre-Check: Download path set To D:\DAT_Folder\StoragePath]LOG]!><time="12:17:40.649 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Starting Download Processes ========]LOG]!><time="12:17:40.665 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Models selected: Lenovo ThinkCentre M720Q]LOG]!><time="12:17:40.665 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Operating System specified: Windows 10]LOG]!><time="12:17:40.680 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Operating System architecture specified: x64]LOG]!><time="12:17:40.680 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Site Code specified: ]LOG]!><time="12:17:40.696 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Download Path specified: D:\DAT_Folder\StoragePath]LOG]!><time="12:17:40.696 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Package Path specified: ]LOG]!><time="12:17:40.712 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Windows 10 build lookup required]LOG]!><time="12:17:40.712 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Windows 10 build 10.0.18362.1 and version 1903 identified for driver match]LOG]!><time="12:17:40.727 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Processing Lenovo ThinkCentre M720Q Downloads ========]LOG]!><time="12:17:40.727 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Starting Download, extract and import processes for Lenovo model: ThinkCentre M720Q]LOG]!><time="12:17:40.743 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Setting Lenovo variables]LOG]!><time="12:17:40.758 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Lenovo ThinkCentre M720Q matching model type: 10T7 10TA 10UA 10TC 10T8 10T9 10U9]LOG]!><time="12:17:40.774 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Looking Up Lenovo ThinkCentre M720Q URL For Windows version win10]LOG]!><time="12:17:40.774 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Driver package URL - https://download.lenovo.com/pccbbs/thinkcentre_drivers/tc_m920t-m920s-m720t-m720s-m920q-m720q-m920x-v530-P330tiny_w1064_1903_201908.exe]LOG]!><time="12:17:40.790 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Lenovo  ThinkCentre M720Q DRIVER PROCESSING STARTED ========]LOG]!><time="12:17:40.805 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== MDT Prerequisites ========]LOG]!><time="12:17:40.821 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[MDT: Importing MDT PowerShell Module]LOG]!><time="12:17:40.821 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== MDT Deployment Share Info ========]LOG]!><time="12:17:40.837 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Found 1 MDT deployment shares available]LOG]!><time="12:17:40.837 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Adding MDT Deployment Share - True]LOG]!><time="12:17:40.852 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Adding MDT Deployment Path - DS001]LOG]!><time="12:17:40.852 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[========  MDT Driver Download ========]LOG]!><time="12:17:40.868 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[MDT: Starting MDT driver download process]LOG]!><time="12:17:40.883 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[MDT: Driver package base location set to D:\DAT_Folder\StoragePath\Lenovo\]LOG]!><time="12:17:40.883 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Lenovo MDT ThinkCentre M720Q PROCESSING FINISHED ========]LOG]!><time="12:17:40.899 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Remaining models to process: 0]LOG]!><time="12:17:40.899 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== FINISHED PROCESSING ========]LOG]!><time="12:17:40.915 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Validating all required selections have been made]LOG]!><time="12:18:05.165 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Validation state is True]LOG]!><time="12:18:05.180 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Importing Into Products: MDT]LOG]!><time="12:18:05.180 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Download Type: Drivers]LOG]!><time="12:18:05.196 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Pre-Check: Download path set To D:\DAT_Folder\StoragePath]LOG]!><time="12:18:05.211 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Starting Download Processes ========]LOG]!><time="12:18:05.227 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Models selected: Lenovo ThinkCentre M720Q]LOG]!><time="12:18:05.227 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Operating System specified: Windows 10]LOG]!><time="12:18:05.243 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Operating System architecture specified: x64]LOG]!><time="12:18:05.243 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Site Code specified: ]LOG]!><time="12:18:05.258 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Download Path specified: D:\DAT_Folder\StoragePath]LOG]!><time="12:18:05.258 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Package Path specified: ]LOG]!><time="12:18:05.274 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Windows 10 build lookup required]LOG]!><time="12:18:05.274 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Windows 10 build 10.0.18362.1 and version 1903 identified for driver match]LOG]!><time="12:18:05.290 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Processing Lenovo ThinkCentre M720Q Downloads ========]LOG]!><time="12:18:05.305 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Starting Download, extract and import processes for Lenovo model: ThinkCentre M720Q]LOG]!><time="12:18:05.305 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Setting Lenovo variables]LOG]!><time="12:18:05.321 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Lenovo ThinkCentre M720Q matching model type: 10T7 10TA 10UA 10TC 10T8 10T9 10U9]LOG]!><time="12:18:05.336 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Looking Up Lenovo ThinkCentre M720Q URL For Windows version win10]LOG]!><time="12:18:05.336 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Driver package URL - https://download.lenovo.com/pccbbs/thinkcentre_drivers/tc_m920t-m920s-m720t-m720s-m920q-m720q-m920x-v530-P330tiny_w1064_1903_201908.exe]LOG]!><time="12:18:05.352 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Lenovo  ThinkCentre M720Q DRIVER PROCESSING STARTED ========]LOG]!><time="12:18:05.368 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== MDT Prerequisites ========]LOG]!><time="12:18:05.383 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[MDT: Importing MDT PowerShell Module]LOG]!><time="12:18:05.383 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== MDT Deployment Share Info ========]LOG]!><time="12:18:05.399 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Found 1 MDT deployment shares available]LOG]!><time="12:18:05.415 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Adding MDT Deployment Share - True]LOG]!><time="12:18:05.415 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Adding MDT Deployment Path - DS001]LOG]!><time="12:18:05.430 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[========  MDT Driver Download ========]LOG]!><time="12:18:05.430 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[MDT: Starting MDT driver download process]LOG]!><time="12:18:05.446 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[MDT: Driver package base location set to D:\DAT_Folder\StoragePath\Lenovo\]LOG]!><time="12:18:05.446 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== Lenovo MDT ThinkCentre M720Q PROCESSING FINISHED ========]LOG]!><time="12:18:05.461 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[Info: Remaining models to process: 0]LOG]!><time="12:18:05.477 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
<![LOG[======== FINISHED PROCESSING ========]LOG]!><time="12:18:05.477 600" date="07-15-2020" component="DriverAutomationTool" context="GIU\administrator" type="1" thread="9076" file="">
`

**Comment by maurice-daly** [comment]
Unfortunately an issue was pointed out to Lenovo in regards to Windows 10 2004 downloads. They updated the XML, however, they also introduced an issue as duplicates and missing entries for Windows 10 1909 were included.

Waiting on a fix from Lenovo..

**Comment by maurice-daly** [comment]
Issue resolved in latest hotfix.

**Comment by Priyankadas24** [comment]
Our driver automation tool is 6.4.9. it is not showing models for Lenovo. Please let us know how to fix this issue. @maurice-daly
