### ISSUE TITLE
what is the current version of Invoke-CMApplyDriverPackage

### ISSUE THREAD

**Issue by rtruss** [maurice-daly/DriverAutomationTool#73]
I see a 4.0.0 but it simply contains several ###  So what is new/updated/fixed in this version?  Thanks in advance,

**Comment by bbrownchg** [comment]
It looks like they're having some difficulty getting files stored in the right place in the repo. I found this, https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1, which has the correct change log information for 4.0.0, and it explains why all of a sudden all of my task sequences were failing!

I wouldn't have updated to 4.0.0 right away if I'd known the Web Service piece was removed. Looks like their blog needs to be updated to detail the new parameters available, too.

**Comment by maurice-daly** [comment]
The deployment scripts are maintained here - https://github.com/MSEndpointMgr/ModernDriverManagement
