### ISSUE TITLE
6.4.5 - URL for MS Product XML no longer working

### ISSUE THREAD

**Issue by agrooms** [maurice-daly/DriverAutomationTool#75]
https://www.scconfigmgr.com/wp-content/uploads/xml/MSProducts.xml
and https://msendpointmgr.com/wp-content/uploads/xml/MSProducts.xml both lead to a 404 Error
on the MSEndpointMgr page.
![Capture](https://user-images.githubusercontent.com/62558261/87671164-7d259d80-c736-11ea-9a8e-ce68c2458d17.JPG)

**Comment by MikeDFW** [comment]
Did you find the solution for this yet? I'm having the same problem.

**Comment by agrooms** [comment]
Short answer - No.

Long answer, I found another on here who recommended pulling a local copy of the XML and editing the PS1 script to point toward the local copy.  I did that and it does identify the desired units correctly now but still doesn't download anything.  As we only have 17 MS SB2 units I just moved on.  They will have to be updated manually 😢

**Comment by maurice-daly** [comment]
Please update to the latest version of the tool. The XML was moved to Gthub.
