### ISSUE TITLE
Dell Flash utility not downloading into the correct location so packages do not create v6.4.8

### ISSUE THREAD

**Issue by MichaelGibsonAltrad** [maurice-daly/DriverAutomationTool#76]
When downloading Dell BIOS files to create a package, the script throws the below error without any detail about what failed.

Error: BIOS flash upgrade utility failed to download. Check log for more details

After looking around it does successfully download the file Flash64W_ZPE.exe to the temp folder, then creates the Flash64Utility folder in the package location as expected. It then tries to find the EXE in the package location to unpack it and fails (as it's only in the temp folder). After placing the EXE in the package location manually and running the process again it got further and unpacked the EXE into that location but the script then failed again because the unpacked Flash64W.exe was not in the temp folder (only in the package folder). To get this to work I needed to make sure that both files were in both locations and the BIOS packages were created correctly in SCCM.

It looks like the folders specified in the scripts are referencing the wrong locations during this function so need re-ordering.

Thanks
Michael

**Comment by maurice-daly** [comment]
Due to changes within the Flash64W_ZPE exe, the DAT was not handling the flash64w.exe being in a subfolder. Code updated, posting hotfix 2 later today.
