### ISSUE TITLE
Version 6.4.8 -Fast Error

### ISSUE THREAD

**Issue by Justin-Curtis-Butler** [maurice-daly/DriverAutomationTool#78]
Getting an output that looks like:

Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.
At line:18124 char:95
 ... ackage -name "*$Model -*$WindowsVersion*$Architecture*" -Fast | Selec ...
                                                             ~~~~~
     CategoryInfo          : InvalidArgument: (:) [Get-CMDriverPackage], ParameterBindingException
    FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.ConfigurationManagement.Cmdlets.Osd.Commands.GetDriverPackageCommand

Looks like in the Base code that comes with the software makes it look like the issue is at line 15380, however finding that location I found several other areas in the code that has the -Fast parameter and it seems to work fine in those locations. Everything seems to work just fine even with the error, but I thought I would mention it.

**Comment by chaosisbliss** [comment]
Hi,

You sure the are all the same. I had the same issue but was able to resolve it by removing the -fast option. There are serveral references to -FAST but for both get-cmdriverpackage and get-cmpackage. One of which does not support the -FAST option. You'll have to test to confirm.

**Comment by johnyoakum** [comment]
I am seeing this as well, even after I removed the -Fast option on the line that is listed in the original issue. I can't find any other reference unless it is in the binary itself where this resides.

**Comment by maurice-daly** [comment]
Code no longer in production release. Closing
