### ISSUE TITLE
Dell E5507 not pulling latest BIOS

### ISSUE THREAD

**Issue by mhouston100** [maurice-daly/DriverAutomationTool#8]
Using Version 6.4.5 and attempting to pull latest BIOS for Dell E5507, nothing happens, it just skips the BIOS.

Checking the download page, the new BIOS downloads exist:

http://downloads.dell.com/published/pages/latitude-e5570-laptop.html

But the tool just finds nothing.

> Info: Validating all required selections have been made	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Validation state is True	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Importing Into Products: ConfigMgr - Standard Pkg	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Download Type: All	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Pre-Check: Download path set To \\nobelium\media\Drivers\PRD - Downloads	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
======== Starting Download Processes ========	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Models selected: Dell Latitude E5570	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Operating System specified: Windows 10	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Operating System architecture specified: x64	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Site Code specified: CMD	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Download Path specified: \\nobelium\media\Drivers\PRD - Downloads	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Package Path specified: \\nobelium\media\Drivers\PRD - Packages	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
======== Processing Dell Latitude E5570 Downloads ========	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Starting Download, extract and import processes for Dell model: Latitude E5570	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Setting Dell variables	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Dell System Model ID is : 06DF	DriverAutomationTool	3/26/2020 8:24:32 AM	12508 (0x30DC)
Info: Using Configuration Manager console BIOS package folder - CMD:\Package\BIOS Packages\Dell	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
Info: Using Configuration Manager console Driver package folder - CMD:\Package\Driver Packages\Dell	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
**======== Dell Latitude E5570 BIOS PROCESSING STARTED ========	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
Info: Attempting to find BIOS link	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
======== Dell Latitude E5570 BIOS PROCESSING FINISHED ========**	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
Info: Driver extract location set - \\nobelium\media\Drivers\PRD - Downloads\Dell\Latitude E5570\Windows10-A17	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
Info: Driver package location set - \\nobelium\media\Drivers\PRD - Packages\Dell\Latitude E5570-Windows10-x64-A17	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
======== Dell ConfigMgr Latitude E5570 DRIVER PROCESSING STARTED ========	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
ConfigMgr: Retrieving driver pack site For Dell Latitude E5570	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
ConfigMgr: URL found: https://downloads.dell.com//techcenter/enterprise-client/w/wiki/11792.latitude-e5570-windows-10-driver-pack	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
ConfigMgr: Latest driver revision found - A17	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
ConfigMgr: Checking ConfigMgr for driver packages matching - Drivers - Dell Latitude E5570 - Windows 10 x64	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
ConfigMgr: Driver package (Drivers - Dell Latitude E5570 - Windows 10 x64 - A17 (CMD005D7)) already exists.	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
======== Dell ConfigMgr Latitude E5570 DRIVER PROCESSING FINISHED ========	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
Info: Remaining models to process: 0	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)
======== FINISHED PROCESSING ========	DriverAutomationTool	3/26/2020 8:24:38 AM	12508 (0x30DC)

Other models, Dell included are working fine, you can see the 5501 download in the log find the correct version etc.

**Comment by maurice-daly** [comment]
This comes up now and again, and all I can do is point out that the lists are provided by the OEM. Again in this instance, there is no 5507 link in the XML provided;

![image](https://user-images.githubusercontent.com/25844716/77589211-2e33ce00-6ee3-11ea-85f0-e9839693d3ce.png)

The alternative is to scrap / parse html pages, which is unreliable and prone to break hence I moved away from that method quite a few years ago. Dell update their XML feeds typically once a month so keep trying ;)

**Comment by mhouston100** [comment]
No sweat, I assumed that it would be the case, the others are all working. 

Yeah trying to head down the 'scraping HTML' path with a company like Dell would be a nightmare.

I'll report it to our Dell account manager and see if they have some sort of channel they can report it up. 

Thanks for getting back so fast!
