### ISSUE TITLE
6.4.8 - Hotfix exe vs ps1 versions

### ISSUE THREAD

**Issue by rtruss** [maurice-daly/DriverAutomationTool#80]
The powershell script is still not updated and github reports it was last updated 22 days ago.  I have lots of Lenovo models I need to update and noticed that the model numbers are indeed missing in the CM Console.  When will the ps1 script file be updated to reflect the exe changes as well?

**Comment by rtruss** [comment]
bump, will you be updating the powershell script as well?  Or did you update it and incorporate it in the installer only?

**Comment by armentpau** [comment]
We are having the same exact issue.  The exe and PS1 are out of date from one another.  It's starting to cause issues for us with them so out of date.

**Comment by armentpau** [comment]
@rtruss You can turn on powershell transcription on your system and run the exe.  This will dump ALL of the PS1 code for you - you can use this until the ps1 gets updated officially on the repo

**Comment by rtruss** [comment]
THANKS for the tip!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by maurice-daly** [comment]
As a general rule. The EXE is the current version, especially if someone needs a quick fix. 

The PS1 and MSI's are updated post updates to the EXEs. I've been flat out with work also, so please remember this is a community solution that is a best endeavour effort to update.

There are updates for the EXE, PS1 and MSI going in later today.
