### ISSUE TITLE
MSProducts.xml System SKU mismatch

### ISSUE THREAD

**Issue by PhilDyer94** [maurice-daly/DriverAutomationTool#81]
Hi,

Noticed this morning when downloading driver packages that the comments field is being populated with incorrect information for two Surface devices:

"Model SystemSKU="Surface_Book_2_1832, Surface_Book_2_1793" ProductName="SurfaceBook" DisplayName="Surface Book""
"Model SystemSKU="Surface_Pro_6_1796_Consumer, Surface_Pro_6_1796_Commercial" ProductName="SurfaceGo" DisplayName="Surface Go""

The Surface Go is an easy fix, but for the Surface Book I can't find any reference on Microsoft docs to what its system sku is due to it being retired, I believe. Also can't find any reference to "Surface_Book_2_1832" only "Surface_Book_1832" which related to the Surface Book 2.

Thanks

Phil

**Comment by cardian** [comment]
The skus for the Surface Laptop / Laptop 2 / Laptop 3 / Go models are mixed up as well.

**Comment by maurice-daly** [comment]
All SKU's have been updated in the XML. The source content for the SKU values is - https://docs.microsoft.com/en-us/surface/surface-system-sku-reference
