### ISSUE TITLE
Import-Module BitsTransfer

### ISSUE THREAD

**Issue by MeneshHarji** [maurice-daly/DriverAutomationTool#82]
Just uploaded to the last versions and now getting this error when importing the driver into SCCM

Error: The 'Get-BitsTransfer' command was found in the module 'BitsTransfer', but the module could not be loaded. For more information, run 'Import-Module BitsTransfer'.

Import-Module : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
At line:162 char:1
+ Import-Module -Name BitsTransfer -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

It seems you need to 

configuration
  startup useLegacyV2RuntimeActivationPolicy="true"
    supportedRuntime version="v4.0"/
  startup
configuration

**Comment by MeneshHarji** [comment]
It seems you need to add 

<configuration>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0"/>
  </startup>
</configuration>

**Comment by dsolodow** [comment]
Looks like the same as #58 .
Guessing it has to do with the version of Windows you're running the tool on?

**Comment by MeneshHarji** [comment]
Its windows 2012 as its hosted on the primary sccm server

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dsolodow** [comment]
Yep, that would do it. 
Short version is pre-Windows 2016 baseline was PowerShell 2.0, which was built on .NET Runtime 2.0, so all the out of box modules are built against the 2.0 runtime. 
Later versions switched to PowerShell 5.1 which uses the .NET Runtime 4.0 and the out of box modules were re-compiled for that. 
Since DAT is built with .NET 4.x, invoking 2.x modules is a PITA.

**Comment by MeneshHarji** [comment]
Working now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MikeDFW** [comment]
I'm on Server 2012, PowerShell 5.1, .NET 4.5, 4.51, 4.52  ..but I'm getting the same error: (@MeneshHarji what was the fix?)

Import-Module : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
At line:162 char:1
+ Import-Module -Name BitsTransfer -Verbose

**Comment by maurice-daly** [comment]
The DriverAutomationTool.exe.config is required, without this you will get this experience on older server versions.
