### ISSUE TITLE
MP instead of Primary site

### ISSUE THREAD

**Issue by rdoloto** [maurice-daly/DriverAutomationTool#88]
Please note  the 6.4.8( hotfix 3) picks  first  MP  as primary site. That works fine if you have Primary site server and MP on the same machine but in bigger environment those roles are split

**Comment by rtruss** [comment]
From what i recall the toolset has always done that, grab your MP vs a site server if not the same box.

**Comment by maurice-daly** [comment]
Detection has been updated in the latest release, but it will fail back to the MP.
