### ISSUE TITLE
Unable to download any of the microsoft drivers

### ISSUE THREAD

**Issue by shwarmy** [maurice-daly/DriverAutomationTool#90]
I am on 6.4.8 hotfix 3 and when i select any of the microsoft devices for 1709, 1809, 1903, and 1909 it goes through its paces but never downloads the files.

======== Starting Download Processes ========	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Models selected: Microsoft Surface Pro 3	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Operating System specified: Windows 10	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Operating System architecture specified: x64	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Site Code specified: SA1	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Download Path specified: E:\Download	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Package Path specified: \\sccm2012r2srv\DriverBiosDistribution\Packages	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Windows 10 build lookup required	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Windows 10 build 10.0.18363.1 and version 1909 identified for driver match	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
======== Processing Microsoft Surface Pro 3 Downloads ========	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Starting Download, extract and import processes for Microsoft model: Surface Pro 3	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Setting Microsoft variables	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Atteming match for SurfacePro3	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Microsoft AKA shortlink URL is https://aka.ms/SurfacePro3/18363	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Microsoft redirected URL discovered is https://www.microsoft.com?ref=aka	DriverAutomationTool	8/3/2020 6:47:55 PM	5172 (0x1434)
Info: Using Configuration Manager console BIOS package folder - SA1:\Package\BIOS Packages\Microsoft	DriverAutomationTool	8/3/2020 6:48:04 PM	5172 (0x1434)
Info: Using Configuration Manager console Driver package folder - SA1:\Package\Driver Packages\Microsoft	DriverAutomationTool	8/3/2020 6:48:04 PM	5172 (0x1434)
Info: Remaining models to process: 0	DriverAutomationTool	8/3/2020 6:48:04 PM	5172 (0x1434)
======== FINISHED PROCESSING ========	DriverAutomationTool	8/3/2020 6:48:04 PM	5172 (0x1434)

**Comment by shwarmy** [comment]
Update. It is only working on version 2004. The prior os versions are not downloading.

**Comment by agrooms** [comment]
Ditto - same issue.  Identifies the units and goes through the paces but doesn't download anything.

**Comment by suprnova74** [comment]
seems the aka.ms url redirects to a basic microsoft Surface page and not any download page. 
```
Info: Microsoft AKA shortlink URL is https://aka.ms/SurfaceLaptop3/19041	DriverAutomationTool	9/2/2020 12:57:40 PM	16064 (0x3EC0)
Info: Microsoft redirected URL discovered is https://www.microsoft.com?ref=aka	DriverAutomationTool	9/2/2020 12:57:41 PM	16064 (0x3EC0)
```

**Comment by maurice-daly** [comment]
The XML is maintained manually at present, and going to each of the links to discover if they support version x of Windows is a bit of a task. So I have added in output to advise if the build specific version can't be found.
