### ISSUE TITLE
Find-LenovoModelType Error

### ISSUE THREAD

**Issue by pgmurphyunc** [maurice-daly/DriverAutomationTool#95]
When I run version 6.4.8, the following error is thrown and the GUI is non-responsive.  The error does not occur in 6.4.6.

Info: Reading driver pack URL - https://download.lenovo.com/cdrt/td/catalogv2.xml

`Exception` calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.`
`Parameter name: length"`
`At line:15231 char:64`
`+ ... Find-LenovoModelType -ModelType $($LenovoKnownModel.Substring(0, 4)))`
`+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException`
`    + FullyQualifiedErrorId : ArgumentOutOfRangeException`
 
`Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.`
`Parameter name: length"`
`At line:15231 char:64`
`+ ... Find-LenovoModelType -ModelType $($LenovoKnownModel.Substring(0, 4)))`
`+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException`
`    + FullyQualifiedErrorId : ArgumentOutOfRangeException`

**Comment by maurice-daly** [comment]
Fixed in version 6.4.9 to be released tomorrow. An oversight with the change in XML formatting from Lenovo
