### ISSUE TITLE
6.4.8 HF 3 - New Install, Dell Catalog Not Download (MS catalog is)

### ISSUE THREAD

**Issue by MikhailCompo** [maurice-daly/DriverAutomationTool#96]
Dell catalog is not being downloaded

Loading module from path 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\BitsTransfer.psd1'.
Loading 'Assembly' from path 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\Microsoft.BackgroundIntelligentTransfer.Management.Interop.dll'.
Loading 'Assembly' from path 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\Microsoft.BackgroundIntelligentTransfer.Management.Interop.dll'.
Loading 'FormatsToProcess' from path 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\BitsTransfer\BitsTransfer.Format.ps1xml'.
Import-Module : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
At line:162 char:1
+ Import-Module -Name BitsTransfer -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Get-Content : Cannot find path 'C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\DriverPackCatalog.xml' because it does not exist.
At line:15087 char:34
+ ... lModelXML = Get-Content -Path (Join-Path -Path $global:TempDirectory  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...PackCatalog.xml:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
You cannot call a method on a null-valued expression.
At line:15089 char:6
+                     $global:DellModelXML.GetType().FullName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Get-Content : Cannot find path 'C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\DriverPackCatalog.xml' because it does not exist.
At line:15087 char:34
+ ... lModelXML = Get-Content -Path (Join-Path -Path $global:TempDirectory  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...PackCatalog.xml:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
You cannot call a method on a null-valued expression.
At line:15089 char:6
+                     $global:DellModelXML.GetType().FullName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by BlueToxic** [comment]
Looks like it's related to #60 .
Try the solution mentioned there, it worked for me.

**Comment by sidans2018** [comment]
download the .csb from here  https://www.dell.com/support/kbdoc/en-us/000122176/driver-pack-catalog 
, extract and place it in temp folder.
