### ISSUE TITLE
Driver Package Path to long

### ISSUE THREAD

**Issue by pintgen** [maurice-daly/DriverAutomationTool#97]
Hi,

first, thanks for the great tool! :-)

Unfortunately today i run into a issue. The destination path where the driverpackages has to be stored was to long, including the driverfiles. 

Our "Package Storage Path" are 74 characters long, then we have additionally 88 characters for the make, model and version and finally the subpath including the files have up to 116 characters. That are 278 characters, what is to much. 

The problem was, that the DAT tool is running without an error oder warning. I can reproduce this with download a HP driverpack and create a custom driverpackage, at  both i see the issue. Log shows also nothing.

We use the version 6.4.6, but i think is not solved in newer versions. 

Best regards,
Andreas

**Comment by MikhailCompo** [comment]
Create a share to the destination folder and use a UNC path instead of a local folder in the settings in DAT.

This is not a DAT problem.

**Comment by pintgen** [comment]
Yes, I have already created a share. ;-)

And of couse the problem was not DAT, but a error or warning for this situation would be very helpful...

**Comment by maurice-daly** [comment]
Warning added into the DAT where your UNC path exceeds 50 characters for the base share value. This will be included in the next post.
