### ISSUE TITLE
BIOS download HP Elitebook XXX G7

### ISSUE THREAD

**Issue by fentax** [maurice-daly/DriverAutomationTool#99]
I think something is missing for the new HP G7 models, not getting any download URL för BIOS for these models. I have tried both HP EliteBook 840 G7 and the 850 G7 and same issue. 

Something wrong with the HP CAB?

======== Hewlett-Packard EliteBook 840 G7 Notebook PC BIOS PROCESSING STARTED ========	
Info: Attempting to find HP BIOS download
Info: Checking for existing HP cabinet file platformList.cab
Info: Downloading HP XML from https://ftp.hp.com/pub/caps-softpaq/cmit/imagepal/ref/platformList.cab	
Info: Expanding HP cabinet file: HPClientDriverPackCatalog.xml
Info: Reading HP XML from C:\Program Files\MSEndpointMgr\Driver Automation Tool\Temp\platformList.xml	
Info: OS pre build strip is 1909
Info: Model is EliteBook 840 G7 Notebook PC
Info: SystemID is 8723
Info: OS is 10.0.1909
Info: Architecture is x64
Info: URL is http://ftp.hp.com/pub/caps-softpaq/cmit/imagepal/ref/8723/8723_64_10.0.1909.cab
Info: Expanding HP SoftPaq cabinet file: 8723_64_10.0.1909.cab
Info: Reading model XML 8723_64_10.0.1909.xml
Info: BIOS download URL is
Warning: Unable to retrieve BIOS Download URL For Hewlett-Packard Client Model: EliteBook 840 G7 Notebook PC	
======== Hewlett-Packard EliteBook 840 G7 Notebook PC BIOS PROCESSING FINISHED ========

**Comment by maurice-daly** [comment]
Issue identified and resolved. Hotfix 2 will be uploaded later today.
